use crate::{HeaderAgent, HeaderOptions};

pub fn render_header(opts: &HeaderOptions, agents: &[HeaderAgent]) -> String {
    let guard = include_guard(&opts.library_name);
    let mut out = String::new();
    out.push_str("// Generated by Corvid — DO NOT EDIT.\n");
    out.push_str("// Phase 22 slice 22-A-cdylib.\n");
    out.push_str("//\n");
    out.push_str("// String ABI ownership for this header:\n");
    out.push_str("//   * inbound `const char*` parameters are UTF-8, null-terminated, caller-owned\n");
    out.push_str("//   * outbound `const char*` returns are UTF-8, null-terminated, Corvid-owned\n");
    out.push_str("//   * release returned strings with `corvid_free_string(...)`\n\n");
    out.push_str(&format!("#ifndef {guard}\n"));
    out.push_str(&format!("#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n\n");
    out.push_str("#ifdef __cplusplus\n");
    out.push_str("extern \"C\" {\n");
    out.push_str("#endif\n\n");

    let has_string_return = agents.iter().any(|agent| agent.return_c_type == "const char*");
    if has_string_return {
        out.push_str("void corvid_free_string(const char* value);\n\n");
    }

    for agent in agents {
        out.push_str(&format!("// {}\n", agent.signature_comment));
        out.push_str(&format!(
            "{} {}({});\n\n",
            agent.return_c_type, agent.name, agent.params_c
        ));
    }

    out.push_str("#ifdef __cplusplus\n");
    out.push_str("}\n");
    out.push_str("#endif\n\n");
    out.push_str(&format!("#endif // {guard}\n"));
    out
}

fn include_guard(library_name: &str) -> String {
    let mut guard = String::from("CORVID_");
    for ch in library_name.chars() {
        if ch.is_ascii_alphanumeric() {
            guard.push(ch.to_ascii_uppercase());
        } else {
            guard.push('_');
        }
    }
    guard.push_str("_H");
    guard
}
