// @generated by corvid bind rust.
// descriptor sha256: b0a8fd4e20c07d83faf63179bbd39053c8eaa3496d6a9e2ea53a9d5750b0c6e5
// corvid-bind version: 0.0.1
// descriptor generated_at: 1970-01-01T00:00:00Z
pub mod common;
pub mod catalog;
pub mod types;
pub mod classify;
pub mod issue_tag;
pub mod grounded_tag;

pub use catalog::{AgentInfo, Catalog, CatalogQuery, FindAgentsStatus, Reversibility};
pub use common::{
    ApprovalDecision, ApprovalRequest, Approver, CallStatus, Client, CorvidError,
    CorvidResult, DescriptorDrift, Grounded, GroundedProvenance, Observation,
    TrustTier, Weak, DESCRIPTOR_HASH_HEX,
};
pub use types::*;
pub use classify::{ClassifyApi, Classify};
pub use issue_tag::{IssueTagApi, IssueTag};
pub use grounded_tag::{GroundedTagApi, GroundedTag};
