// @generated by corvid bind rust.
// descriptor sha256: a4cf8eb8bbed8655b4aa52860f4f7105e7ba60dacfd96c228a474607173134ae
// corvid-bind version: 0.0.1
// descriptor generated_at: 1970-01-01T00:00:00Z
use std::ffi::CString;

use libloading::Symbol;
use serde_json::json;

use crate::common::{
    take_owned_c_string, ApprovalDecision, Approver, CallAttempt, CallStatus, Client,
    CorvidError, CorvidResult, Grounded, Observation, TrustTier,
};
use crate::types::*;

pub struct GroundedTag;

impl GroundedTag {
    pub const NAME: &str = "grounded_tag";
    pub const SYMBOL: &str = "grounded_tag";
    pub const TRUST_TIER: TrustTier = TrustTier::Autonomous;
    pub const COST_BOUND_USD: Option<f64> = Some(0.01);
    pub const IS_DANGEROUS: bool = false;
    pub const RETURNS_GROUNDED: bool = true;
}

pub trait GroundedTagApi {
    fn grounded_tag(&self, tag: &str) -> CorvidResult<(Grounded<String>, Observation)>;
}

impl GroundedTagApi for Client {
    fn grounded_tag(&self, tag: &str) -> CorvidResult<(Grounded<String>, Observation)> {
        let arg_0 = CString::new(tag).map_err(|err| CorvidError::BadArgs(err.to_string()))?;
        unsafe {
            let symbol: Symbol<unsafe extern "C" fn(*const std::ffi::c_char, *mut u64, *mut u64) -> *const std::ffi::c_char> = self.library.get(b"grounded_tag").map_err(|err| CorvidError::Load(err.to_string()))?;
            let mut grounded_handle = 0u64;
            let mut observation_handle = 0u64;
            let value = symbol(arg_0.as_ptr(), &mut grounded_handle, &mut observation_handle);
            let payload = take_owned_c_string(&self.library, value, "corvid_free_string")?;
            let grounded = Grounded::new(payload, self.library.clone(), grounded_handle, "corvid_grounded_release");
            Ok((grounded, Observation::new(self.library.clone(), observation_handle, "corvid_observation_release")))
        }
    }
}
