// @generated by corvid bind rust.
// descriptor sha256: a4cf8eb8bbed8655b4aa52860f4f7105e7ba60dacfd96c228a474607173134ae
// corvid-bind version: 0.0.1
// descriptor generated_at: 1970-01-01T00:00:00Z

use serde::{Deserialize, Serialize};

