use clap::Subcommand;
use std::path::PathBuf;

#[derive(Subcommand)]
pub enum AuthCommand {
    /// Initialise both the auth store (sessions / API keys /
    /// OAuth state) and the approval queue store. Idempotent —
    /// safe to re-run on every deploy.
    Migrate {
        #[arg(long, value_name = "PATH", default_value = "target/auth.db")]
        auth_state: PathBuf,
        #[arg(long, value_name = "PATH", default_value = "target/approvals.db")]
        approvals_state: PathBuf,
    },
    /// Manage API keys for service actors.
    Keys {
        #[command(subcommand)]
        command: AuthKeysCommand,
    },
}

#[derive(Subcommand)]
pub enum AuthKeysCommand {
    /// Issue a new API key. The raw key is supplied by the caller
    /// (typically generated by an HMAC-SHA256 of a host RNG seed
    /// in the deploy pipeline) and stored only as an Argon2id
    /// hash. The raw value is echoed back in the output once.
    Issue {
        #[arg(long, value_name = "PATH", default_value = "target/auth.db")]
        auth_state: PathBuf,
        #[arg(long)]
        key_id: String,
        #[arg(long)]
        service_actor: String,
        #[arg(long)]
        tenant: String,
        #[arg(long)]
        raw_key: String,
        #[arg(long, default_value = "scope:default")]
        scope_fingerprint: String,
        #[arg(long, default_value = "Service")]
        display_name: String,
        /// Expiry timestamp in milliseconds since epoch. Defaults
        /// to never (u64::MAX).
        #[arg(long)]
        expires_at_ms: Option<u64>,
    },
    /// Revoke a previously-issued API key. Idempotent.
    Revoke {
        #[arg(long, value_name = "PATH", default_value = "target/auth.db")]
        auth_state: PathBuf,
        #[arg(long)]
        key_id: String,
    },
    /// Rotate an API key: revoke the old key, create a new key
    /// with the same scope fingerprint for the same service actor.
    Rotate {
        #[arg(long, value_name = "PATH", default_value = "target/auth.db")]
        auth_state: PathBuf,
        #[arg(long)]
        key_id: String,
        #[arg(long)]
        service_actor: String,
        #[arg(long)]
        tenant: String,
        #[arg(long)]
        new_key_id: String,
        #[arg(long)]
        new_raw_key: String,
        #[arg(long)]
        expires_at_ms: Option<u64>,
    },
}
