//! LLM-generated narrative summary for `corvid trace-diff`
//! receipts. Opt-in via `--narrative=auto|on|off`.
//!
//! The narrative is a one-to-three-sentence prose paragraph that
//! opens the receipt. It is generated by a Corvid `summarise_diff`
//! prompt consuming a `DiffSummary` (the canonical set of algebraic
//! deltas Rust computes from the base + head descriptors). The
//! prompt returns a `ReceiptNarrative { body, citations }`; Rust
//! validates the citations against the delta-key allow-list before
//! passing the narrative to `review_pr`. When validation fails or
//! the mode is `off`, the narrative is replaced with the empty
//! sentinel and `review_pr` renders the pre-H-4 boilerplate header.
//!
//! Citation validation is strict (all-or-nothing): every cited
//! `delta_key` must be in the allow-list, a non-empty body requires
//! at least one citation, and no delta_key may appear twice. Any
//! violation rejects the whole narrative.
//!
//! This module does not talk to the Corvid VM — it owns the
//! Rust-side shape of the types, the delta-key computation, the
//! validation logic, and the `--narrative` mode enum. Runtime
//! invocation of the prompt itself lives in
//! [`reviewer_invocation`], which calls back here for validation.

use std::collections::HashSet;
use std::str::FromStr;

use corvid_abi::{
    AbiAgent, AbiApprovalContract, AbiOwnership, AbiOwnershipMode, AbiParam,
    AbiProvenanceContract, CorvidAbi, ScalarTypeName, TypeDescription,
};
use serde::{Deserialize, Serialize};

/// Which narrative path `corvid trace-diff` should take.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NarrativeMode {
    /// Generate the narrative when an LLM adapter is configured
    /// (via `CORVID_MODEL` + either `ANTHROPIC_API_KEY` or
    /// `OPENAI_API_KEY`). Silently fall back to the H-3 boilerplate
    /// header when no adapter is present. This is the default so
    /// normal local use doesn't require any extra flags.
    Auto,
    /// Generate the narrative unconditionally. Hard-fail if no
    /// adapter is configured — the caller opted in and should know
    /// their environment doesn't support the feature.
    On,
    /// Skip the prompt entirely. CI and deterministic reproducers
    /// pick this to ensure receipts are byte-stable across reruns.
    Off,
}

impl Default for NarrativeMode {
    fn default() -> Self {
        NarrativeMode::Auto
    }
}

impl FromStr for NarrativeMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "auto" => Ok(NarrativeMode::Auto),
            "on" => Ok(NarrativeMode::On),
            "off" => Ok(NarrativeMode::Off),
            other => Err(format!(
                "unknown narrative mode `{other}`; expected `auto`, `on`, or `off`"
            )),
        }
    }
}

/// A single algebraic delta, addressable by a canonical key. Mirror
/// of the reviewer's `DeltaRecord` type field-for-field; coerced
/// through `json_to_value` at the FFI boundary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct DeltaRecord {
    pub key: String,
    pub summary: String,
}

/// Full set of deltas Rust hands to `summarise_diff` and checks
/// citations against. Mirror of the reviewer's `DiffSummary`.
#[derive(Debug, Clone, Serialize)]
pub struct DiffSummary {
    pub records: Vec<DeltaRecord>,
}

impl DiffSummary {
    /// Allow-list of delta keys for citation validation. Owning a
    /// `HashSet` here keeps the `O(1)` lookup against the list of
    /// cited keys; `DiffSummary` itself stays a `Vec` because the
    /// reviewer iterates in order.
    pub fn key_set(&self) -> HashSet<&str> {
        self.records.iter().map(|r| r.key.as_str()).collect()
    }
}

/// Single citation the LLM attaches to a phrase. Mirror of the
/// reviewer's `DeltaCitation`. `Serialize` so a validated
/// `ReceiptNarrative` can round-trip back to `review_pr` through
/// `json_to_value`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeltaCitation {
    pub delta_key: String,
}

/// Prose summary + structured citations. Mirror of the reviewer's
/// `ReceiptNarrative`. `Serialize` so Rust can pass a validated
/// narrative back through `json_to_value` into `review_pr`;
/// `Deserialize` so Rust can coerce the LLM's output back into a
/// Rust struct for validation.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ReceiptNarrative {
    pub body: String,
    #[serde(default)]
    pub citations: Vec<DeltaCitation>,
}

impl ReceiptNarrative {
    /// Sentinel used whenever the narrative path is skipped (mode
    /// = `Off`, no adapter under `Auto`) or when Rust rejects a
    /// generated narrative. `review_pr` treats `body == ""` as the
    /// signal to render the H-3 boilerplate header.
    pub fn empty() -> Self {
        Self {
            body: String::new(),
            citations: Vec::new(),
        }
    }
}

/// Why Rust rejected an LLM-generated narrative. Returned by
/// [`validate_narrative`] so the CLI can emit a human-readable
/// `narrative rejected: <reason>` line on stderr before falling
/// back to boilerplate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NarrativeRejection {
    /// The narrative referenced at least one delta key that is
    /// not in the diff allow-list. Carries the first offending
    /// key so the operator can grep the trace to understand what
    /// the model hallucinated.
    UnknownCitationKey(String),
    /// The narrative body is non-empty but the citations list is
    /// empty. The prompt's whole point is that prose stays
    /// tethered to specific deltas; empty citations mean
    /// decorative grounding, which Dev B explicitly vetoed.
    NonEmptyBodyWithoutCitations,
    /// A delta key appears more than once in the citations. Hint
    /// that the model restated the same grounding. Strict rule
    /// from the pre-phase chat.
    DuplicateCitationKey(String),
}

impl std::fmt::Display for NarrativeRejection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NarrativeRejection::UnknownCitationKey(k) => {
                write!(f, "unknown citation key `{k}`")
            }
            NarrativeRejection::NonEmptyBodyWithoutCitations => {
                write!(f, "non-empty body with empty citations list")
            }
            NarrativeRejection::DuplicateCitationKey(k) => {
                write!(f, "duplicate citation key `{k}`")
            }
        }
    }
}

/// Strict all-or-nothing validation. Returns `Ok(())` if the
/// narrative is acceptable, `Err(NarrativeRejection)` otherwise.
/// The caller on rejection emits a stderr warning and substitutes
/// `ReceiptNarrative::empty()`.
pub fn validate_narrative(
    narrative: &ReceiptNarrative,
    diff: &DiffSummary,
) -> Result<(), NarrativeRejection> {
    if narrative.body.is_empty() && narrative.citations.is_empty() {
        // The empty sentinel is always acceptable — it's what we'll
        // substitute on rejection anyway, and it's the natural
        // prompt output when there were no deltas to describe.
        return Ok(());
    }

    if !narrative.body.is_empty() && narrative.citations.is_empty() {
        return Err(NarrativeRejection::NonEmptyBodyWithoutCitations);
    }

    let allow = diff.key_set();
    let mut seen: HashSet<&str> = HashSet::new();
    for cite in &narrative.citations {
        if !allow.contains(cite.delta_key.as_str()) {
            return Err(NarrativeRejection::UnknownCitationKey(
                cite.delta_key.clone(),
            ));
        }
        if !seen.insert(cite.delta_key.as_str()) {
            return Err(NarrativeRejection::DuplicateCitationKey(
                cite.delta_key.clone(),
            ));
        }
    }
    Ok(())
}

/// Compute the canonical delta-record set from the base + head
/// descriptors. This is the single source of truth for the
/// allow-list that validates narrative citations; it also becomes
/// the structured input to `summarise_diff`.
///
/// Record keys follow a dot-separated category, colon-separated
/// variadic-args grammar so hosts and future slices can parse
/// them deterministically:
///
///   - `agent.added:<name>`
///   - `agent.removed:<name>`
///   - `agent.trust_tier_changed:<name>:<from>-><to>`
///   - `agent.dangerous_gained:<name>` / `agent.dangerous_lost:<name>`
///   - `agent.replayable_gained:<name>` / `agent.replayable_lost:<name>`
///   - `agent.approval.label_added:<name>:<label>`
///   - `agent.approval.label_removed:<name>:<label>`
///   - `agent.approval.tier_changed:<name>:<label>:<from>-><to>`
///   - `agent.approval.reversibility_changed:<name>:<label>:<from>-><to>`
///   - `agent.provenance.grounded_gained:<name>` /
///     `agent.provenance.grounded_lost:<name>`
///   - `agent.provenance.dep_added:<name>:<dep>` /
///     `agent.provenance.dep_removed:<name>:<dep>`
///   - `agent.extern.ownership_changed:<name>:ret:<from>-><to>`
///   - `agent.extern.ownership_changed:<name>:arg[<idx>]:<from>-><to>`
///
/// The keys stay stable between record emission here and the
/// matching rendering in `reviewer.cor` by convention: any new
/// delta type must be added to both sides. The `reviewer_source_compiles`
/// test is the smoke-test backstop.
pub fn compute_diff_summary(base: &CorvidAbi, head: &CorvidAbi) -> DiffSummary {
    let mut records = Vec::new();

    let base_agents: std::collections::BTreeMap<&str, &AbiAgent> =
        base.agents.iter().map(|a| (a.name.as_str(), a)).collect();
    let head_agents: std::collections::BTreeMap<&str, &AbiAgent> =
        head.agents.iter().map(|a| (a.name.as_str(), a)).collect();

    for (name, ba) in &base_agents {
        match head_agents.get(name) {
            None => records.push(DeltaRecord {
                key: format!("agent.removed:{name}"),
                summary: format!("agent `{name}` removed from the exported surface"),
            }),
            Some(ha) => {
                diff_agent_pair(name, ba, ha, &mut records);
            }
        }
    }
    for (name, ha) in &head_agents {
        if !base_agents.contains_key(name) {
            records.push(DeltaRecord {
                key: format!("agent.added:{name}"),
                summary: format!("new agent `{name}` added to the exported surface"),
            });
            // An agent that's new on the head side can also carry
            // initial approval labels / grounded deps; we surface
            // those as explicit deltas too so the prompt can cite
            // them. This mirrors the reviewer's render — a new
            // agent is never "silent" about its contract shape.
            emit_initial_contract(ha, &mut records);
        }
    }

    DiffSummary { records }
}

fn diff_agent_pair(name: &str, base: &AbiAgent, head: &AbiAgent, out: &mut Vec<DeltaRecord>) {
    let base_tier = base
        .effects
        .trust_tier
        .clone()
        .unwrap_or_else(|| "unspecified".to_string());
    let head_tier = head
        .effects
        .trust_tier
        .clone()
        .unwrap_or_else(|| "unspecified".to_string());
    if base_tier != head_tier {
        out.push(DeltaRecord {
            key: format!("agent.trust_tier_changed:{name}:{base_tier}->{head_tier}"),
            summary: format!(
                "agent `{name}` trust-tier changed from `{base_tier}` to `{head_tier}`"
            ),
        });
    }

    if base.attributes.dangerous != head.attributes.dangerous {
        if head.attributes.dangerous {
            out.push(DeltaRecord {
                key: format!("agent.dangerous_gained:{name}"),
                summary: format!("agent `{name}` became `@dangerous`"),
            });
        } else {
            out.push(DeltaRecord {
                key: format!("agent.dangerous_lost:{name}"),
                summary: format!("agent `{name}` no longer `@dangerous`"),
            });
        }
    }
    if base.attributes.replayable != head.attributes.replayable {
        if head.attributes.replayable {
            out.push(DeltaRecord {
                key: format!("agent.replayable_gained:{name}"),
                summary: format!("agent `{name}` gained `@replayable`"),
            });
        } else {
            out.push(DeltaRecord {
                key: format!("agent.replayable_lost:{name}"),
                summary: format!("agent `{name}` lost `@replayable`"),
            });
        }
    }

    diff_approval(name, &base.approval_contract, &head.approval_contract, out);
    diff_provenance(name, &base.provenance, &head.provenance, out);
    diff_ownership(name, base, head, out);
}

fn diff_approval(
    name: &str,
    base: &AbiApprovalContract,
    head: &AbiApprovalContract,
    out: &mut Vec<DeltaRecord>,
) {
    let base_labels: std::collections::BTreeMap<&str, &corvid_abi::AbiApprovalLabel> =
        base.labels.iter().map(|l| (l.label.as_str(), l)).collect();
    let head_labels: std::collections::BTreeMap<&str, &corvid_abi::AbiApprovalLabel> =
        head.labels.iter().map(|l| (l.label.as_str(), l)).collect();

    for (label, bl) in &base_labels {
        match head_labels.get(label) {
            None => out.push(DeltaRecord {
                key: format!("agent.approval.label_removed:{name}:{label}"),
                summary: format!("approve site `{label}` removed from agent `{name}`"),
            }),
            Some(hl) => {
                let bt = bl
                    .required_tier
                    .clone()
                    .unwrap_or_else(|| "unspecified".to_string());
                let ht = hl
                    .required_tier
                    .clone()
                    .unwrap_or_else(|| "unspecified".to_string());
                if bt != ht {
                    out.push(DeltaRecord {
                        key: format!(
                            "agent.approval.tier_changed:{name}:{label}:{bt}->{ht}"
                        ),
                        summary: format!(
                            "approve site `{label}` on agent `{name}` required-tier changed from `{bt}` to `{ht}`"
                        ),
                    });
                }
                let br = bl
                    .reversibility
                    .clone()
                    .unwrap_or_else(|| "unspecified".to_string());
                let hr = hl
                    .reversibility
                    .clone()
                    .unwrap_or_else(|| "unspecified".to_string());
                if br != hr {
                    out.push(DeltaRecord {
                        key: format!(
                            "agent.approval.reversibility_changed:{name}:{label}:{br}->{hr}"
                        ),
                        summary: format!(
                            "approve site `{label}` on agent `{name}` reversibility changed from `{br}` to `{hr}`"
                        ),
                    });
                }
            }
        }
    }
    for (label, _hl) in &head_labels {
        if !base_labels.contains_key(label) {
            out.push(DeltaRecord {
                key: format!("agent.approval.label_added:{name}:{label}"),
                summary: format!("approve site `{label}` added to agent `{name}`"),
            });
        }
    }
}

fn diff_provenance(
    name: &str,
    base: &AbiProvenanceContract,
    head: &AbiProvenanceContract,
    out: &mut Vec<DeltaRecord>,
) {
    if base.returns_grounded != head.returns_grounded {
        if head.returns_grounded {
            out.push(DeltaRecord {
                key: format!("agent.provenance.grounded_gained:{name}"),
                summary: format!(
                    "agent `{name}` return value gained `Grounded<T>` provenance"
                ),
            });
        } else {
            out.push(DeltaRecord {
                key: format!("agent.provenance.grounded_lost:{name}"),
                summary: format!(
                    "agent `{name}` return value lost `Grounded<T>` provenance"
                ),
            });
        }
    }
    let base_deps: HashSet<&str> = base.grounded_param_deps.iter().map(|s| s.as_str()).collect();
    let head_deps: HashSet<&str> = head.grounded_param_deps.iter().map(|s| s.as_str()).collect();
    // Iterate in sorted order (via the Vec under the hood) to keep
    // the diff deterministic across HashSet iteration orders.
    for dep in &base.grounded_param_deps {
        if !head_deps.contains(dep.as_str()) {
            out.push(DeltaRecord {
                key: format!("agent.provenance.dep_removed:{name}:{dep}"),
                summary: format!(
                    "agent `{name}` lost grounded dependency on parameter `{dep}`"
                ),
            });
        }
    }
    for dep in &head.grounded_param_deps {
        if !base_deps.contains(dep.as_str()) {
            out.push(DeltaRecord {
                key: format!("agent.provenance.dep_added:{name}:{dep}"),
                summary: format!(
                    "agent `{name}` gained grounded dependency on parameter `{dep}`"
                ),
            });
        }
    }
}

fn diff_ownership(name: &str, base: &AbiAgent, head: &AbiAgent, out: &mut Vec<DeltaRecord>) {
    let base_return = ownership_label(&effective_return_ownership(base));
    let head_return = ownership_label(&effective_return_ownership(head));
    if base_return != head_return {
        out.push(DeltaRecord {
            key: format!(
                "agent.extern.ownership_changed:{name}:ret:{base_return}->{head_return}"
            ),
            summary: format!(
                "agent `{name}` return ownership changed from `{base_return}` to `{head_return}`"
            ),
        });
    }

    for (index, (base_param, head_param)) in base.params.iter().zip(head.params.iter()).enumerate() {
        let base_label = ownership_label(&effective_param_ownership(base_param));
        let head_label = ownership_label(&effective_param_ownership(head_param));
        if base_label != head_label {
            out.push(DeltaRecord {
                key: format!(
                    "agent.extern.ownership_changed:{name}:arg[{index}]:{base_label}->{head_label}"
                ),
                summary: format!(
                    "agent `{name}` argument #{index} ownership changed from `{base_label}` to `{head_label}`"
                ),
            });
        }
    }
}

/// When an agent is new under head, surface its initial approval
/// labels + grounded contract as explicit deltas too — otherwise
/// the narrative could only cite `agent.added:*` and wouldn't be
/// able to say anything about the agent's shape.
fn emit_initial_contract(agent: &AbiAgent, out: &mut Vec<DeltaRecord>) {
    let name = agent.name.as_str();
    for label in &agent.approval_contract.labels {
        out.push(DeltaRecord {
            key: format!("agent.approval.label_added:{name}:{}", label.label),
            summary: format!(
                "approve site `{}` declared on new agent `{name}`",
                label.label
            ),
        });
    }
    if agent.provenance.returns_grounded {
        out.push(DeltaRecord {
            key: format!("agent.provenance.grounded_gained:{name}"),
            summary: format!(
                "new agent `{name}` returns `Grounded<T>`"
            ),
        });
    }
    for dep in &agent.provenance.grounded_param_deps {
        out.push(DeltaRecord {
            key: format!("agent.provenance.dep_added:{name}:{dep}"),
            summary: format!(
                "new agent `{name}` declares grounded dependency on `{dep}`"
            ),
        });
    }
}

fn effective_param_ownership(param: &AbiParam) -> AbiOwnership {
    param.ownership.clone().unwrap_or_else(|| match &param.ty {
        TypeDescription::Scalar {
            scalar: ScalarTypeName::String | ScalarTypeName::TraceId,
        } => AbiOwnership {
            mode: AbiOwnershipMode::Borrowed,
            lifetime: Some("call".to_string()),
            destructor: None,
        },
        _ => AbiOwnership {
            mode: AbiOwnershipMode::Owned,
            lifetime: None,
            destructor: None,
        },
    })
}

fn effective_return_ownership(agent: &AbiAgent) -> AbiOwnership {
    agent.return_ownership.clone().unwrap_or_else(|| match &agent.return_type {
        TypeDescription::Grounded { .. } => AbiOwnership {
            mode: AbiOwnershipMode::Owned,
            lifetime: None,
            destructor: Some(corvid_abi::AbiDestructor {
                kind: corvid_abi::AbiDestructorKind::Release,
                symbol: "corvid_grounded_release".to_string(),
            }),
        },
        TypeDescription::Scalar {
            scalar: ScalarTypeName::String | ScalarTypeName::TraceId,
        } => AbiOwnership {
            mode: AbiOwnershipMode::Owned,
            lifetime: None,
            destructor: Some(corvid_abi::AbiDestructor {
                kind: corvid_abi::AbiDestructorKind::Drop,
                symbol: "corvid_free_string".to_string(),
            }),
        },
        _ => AbiOwnership {
            mode: AbiOwnershipMode::Owned,
            lifetime: None,
            destructor: None,
        },
    })
}

fn ownership_label(ownership: &AbiOwnership) -> String {
    match ownership.mode {
        AbiOwnershipMode::Owned => "@owned".to_string(),
        AbiOwnershipMode::Borrowed => match ownership.lifetime.as_deref() {
            Some("call") | None => "@borrowed".to_string(),
            Some(lifetime) => format!("@borrowed<'{lifetime}>"),
        },
        AbiOwnershipMode::Shared => "@shared".to_string(),
        AbiOwnershipMode::Static => "@static".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn narr(body: &str, keys: &[&str]) -> ReceiptNarrative {
        ReceiptNarrative {
            body: body.to_string(),
            citations: keys
                .iter()
                .map(|k| DeltaCitation {
                    delta_key: k.to_string(),
                })
                .collect(),
        }
    }

    fn summary_with(keys: &[&str]) -> DiffSummary {
        DiffSummary {
            records: keys
                .iter()
                .map(|k| DeltaRecord {
                    key: k.to_string(),
                    summary: format!("summary for {k}"),
                })
                .collect(),
        }
    }

    #[test]
    fn mode_parses_from_str() {
        assert_eq!("auto".parse::<NarrativeMode>().unwrap(), NarrativeMode::Auto);
        assert_eq!("on".parse::<NarrativeMode>().unwrap(), NarrativeMode::On);
        assert_eq!("off".parse::<NarrativeMode>().unwrap(), NarrativeMode::Off);
        assert!("wat".parse::<NarrativeMode>().is_err());
    }

    #[test]
    fn validate_accepts_empty_sentinel() {
        let empty = ReceiptNarrative::empty();
        let diff = summary_with(&["agent.added:foo"]);
        assert!(validate_narrative(&empty, &diff).is_ok());
    }

    #[test]
    fn validate_accepts_well_formed_narrative() {
        let narrative = narr(
            "Agent `foo` was added.",
            &["agent.added:foo"],
        );
        let diff = summary_with(&["agent.added:foo"]);
        assert!(validate_narrative(&narrative, &diff).is_ok());
    }

    #[test]
    fn validate_rejects_unknown_citation_key() {
        let narrative = narr(
            "Agent `foo` was added.",
            &["agent.added:hallucinated"],
        );
        let diff = summary_with(&["agent.added:foo"]);
        match validate_narrative(&narrative, &diff) {
            Err(NarrativeRejection::UnknownCitationKey(k)) => {
                assert_eq!(k, "agent.added:hallucinated");
            }
            other => panic!("expected UnknownCitationKey, got {other:?}"),
        }
    }

    #[test]
    fn validate_rejects_empty_citations_with_body() {
        let narrative = narr("Agent `foo` was added.", &[]);
        let diff = summary_with(&["agent.added:foo"]);
        assert_eq!(
            validate_narrative(&narrative, &diff).unwrap_err(),
            NarrativeRejection::NonEmptyBodyWithoutCitations
        );
    }

    #[test]
    fn validate_rejects_duplicate_citation_key() {
        let narrative = narr(
            "Agent `foo` was added (added).",
            &["agent.added:foo", "agent.added:foo"],
        );
        let diff = summary_with(&["agent.added:foo"]);
        match validate_narrative(&narrative, &diff) {
            Err(NarrativeRejection::DuplicateCitationKey(k)) => {
                assert_eq!(k, "agent.added:foo");
            }
            other => panic!("expected DuplicateCitationKey, got {other:?}"),
        }
    }

    fn synth_abi_minimal(
        name: &str,
        trust: &str,
        dangerous: bool,
        replayable: bool,
    ) -> CorvidAbi {
        let agent_json = serde_json::json!({
            "name": name,
            "symbol": name,
            "source_span": { "start": 0, "end": 0 },
            "params": [],
            "return_type": { "kind": "scalar", "scalar": "Int" },
            "effects": { "trust_tier": trust },
            "attributes": {
                "replayable": replayable,
                "deterministic": false,
                "dangerous": dangerous,
                "pub_extern_c": false
            },
            "approval_contract": { "required": dangerous, "labels": [] },
            "provenance": { "returns_grounded": false, "grounded_param_deps": [] }
        });
        let json = serde_json::json!({
            "corvid_abi_version": corvid_abi::CORVID_ABI_VERSION,
            "compiler_version": "test",
            "source_path": "test.cor",
            "generated_at": "1970-01-01T00:00:00Z",
            "agents": [agent_json],
            "prompts": [],
            "tools": [],
            "types": [],
            "approval_sites": []
        });
        corvid_abi::descriptor_from_json(&serde_json::to_string(&json).unwrap()).unwrap()
    }

    #[test]
    fn diff_summary_detects_added_agent() {
        let base = synth_abi_minimal("classify", "autonomous", false, true);
        // Head has both agents; base only has classify.
        let head_json = serde_json::json!({
            "corvid_abi_version": corvid_abi::CORVID_ABI_VERSION,
            "compiler_version": "test",
            "source_path": "test.cor",
            "generated_at": "1970-01-01T00:00:00Z",
            "agents": [
                {
                    "name": "classify", "symbol": "classify",
                    "source_span": { "start": 0, "end": 0 },
                    "params": [], "return_type": { "kind": "scalar", "scalar": "Int" },
                    "effects": { "trust_tier": "autonomous" },
                    "attributes": {
                        "replayable": true, "deterministic": false,
                        "dangerous": false, "pub_extern_c": false
                    },
                    "approval_contract": { "required": false, "labels": [] },
                    "provenance": { "returns_grounded": false, "grounded_param_deps": [] }
                },
                {
                    "name": "summarize", "symbol": "summarize",
                    "source_span": { "start": 0, "end": 0 },
                    "params": [], "return_type": { "kind": "scalar", "scalar": "Int" },
                    "effects": { "trust_tier": "autonomous" },
                    "attributes": {
                        "replayable": true, "deterministic": false,
                        "dangerous": false, "pub_extern_c": false
                    },
                    "approval_contract": { "required": false, "labels": [] },
                    "provenance": { "returns_grounded": false, "grounded_param_deps": [] }
                }
            ],
            "prompts": [], "tools": [], "types": [], "approval_sites": []
        });
        let head: CorvidAbi =
            corvid_abi::descriptor_from_json(&serde_json::to_string(&head_json).unwrap()).unwrap();
        let diff = compute_diff_summary(&base, &head);
        assert!(
            diff.records
                .iter()
                .any(|r| r.key == "agent.added:summarize"),
            "got: {:?}",
            diff.records
        );
    }

    #[test]
    fn diff_summary_detects_trust_tier_change() {
        let base = synth_abi_minimal("refund_bot", "human_required", false, false);
        let head = synth_abi_minimal("refund_bot", "autonomous", false, false);
        let diff = compute_diff_summary(&base, &head);
        assert!(diff
            .records
            .iter()
            .any(|r| r.key
                == "agent.trust_tier_changed:refund_bot:human_required->autonomous"));
    }

    #[test]
    fn diff_summary_detects_dangerous_transition() {
        let base = synth_abi_minimal("refund_bot", "human_required", false, false);
        let head = synth_abi_minimal("refund_bot", "human_required", true, false);
        let diff = compute_diff_summary(&base, &head);
        assert!(diff
            .records
            .iter()
            .any(|r| r.key == "agent.dangerous_gained:refund_bot"));
    }

    #[test]
    fn diff_summary_empty_when_sides_match() {
        let base = synth_abi_minimal("classify", "autonomous", false, true);
        let head = synth_abi_minimal("classify", "autonomous", false, true);
        let diff = compute_diff_summary(&base, &head);
        assert!(diff.records.is_empty(), "got: {:?}", diff.records);
    }
}
