use crate::error::WasmCodegenError;
use crate::WasmHostImport;
use corvid_ir::IrAgent;
use corvid_types::Type;
use serde::Serialize;

#[derive(Debug, Clone)]
pub struct WasmArtifacts {
    pub wasm: Vec<u8>,
    pub js_loader: String,
    pub ts_types: String,
    pub manifest_json: String,
}

#[derive(Debug, Serialize)]
struct WasmManifest {
    schema_version: u32,
    module_name: String,
    target: &'static str,
    exports: Vec<WasmExport>,
    imports: Vec<WasmImport>,
    host_capability_abi: &'static str,
    non_scope: Vec<&'static str>,
}

#[derive(Debug, Serialize)]
struct WasmExport {
    name: String,
    params: Vec<WasmParam>,
    return_type: String,
}

#[derive(Debug, Serialize)]
struct WasmParam {
    name: String,
    ty: String,
}

#[derive(Debug, Serialize)]
struct WasmImport {
    kind: &'static str,
    source_name: String,
    import_module: &'static str,
    import_name: String,
    params: Vec<WasmParam>,
    return_type: String,
}

pub(crate) fn build_artifacts(
    module_name: &str,
    agents: &[&IrAgent],
    imports: &[WasmHostImport],
    wasm: Vec<u8>,
) -> Result<WasmArtifacts, WasmCodegenError> {
    Ok(WasmArtifacts {
        wasm,
        js_loader: emit_js_loader(module_name, agents, imports)?,
        ts_types: emit_ts_types(agents, imports)?,
        manifest_json: emit_manifest(module_name, agents, imports)?,
    })
}

fn ts_type(ty: &Type) -> Result<&'static str, WasmCodegenError> {
    match ty {
        Type::Int => Ok("bigint"),
        Type::Float => Ok("number"),
        Type::Bool => Ok("boolean"),
        Type::Nothing => Ok("void"),
        _ => Err(WasmCodegenError::unsupported(format!(
            "unsupported TypeScript wasm surface type `{}`",
            ty.display_name()
        ))),
    }
}

fn js_return_expr(name: &str, ty: &Type) -> String {
    match ty {
        Type::Bool => "Boolean(result)".into(),
        Type::Nothing => "undefined".into(),
        _ => name.into(),
    }
}

fn emit_js_loader(
    module_name: &str,
    agents: &[&IrAgent],
    imports: &[WasmHostImport],
) -> Result<String, WasmCodegenError> {
    let mut out = String::new();
    out.push_str("// Auto-generated by Corvid. Do not edit.\n");
    out.push_str(&format!(
        "const WASM_URL = new URL('./{module_name}.wasm', import.meta.url);\n\n"
    ));
    out.push_str("function missing(kind, name) {\n");
    out.push_str("  throw new Error(`Corvid WASM host ${kind} '${name}' is not provided`);\n");
    out.push_str("}\n\n");
    out.push_str("export function adaptImports(host = {}) {\n");
    out.push_str("  return {\n");
    out.push_str("    'corvid:host': {\n");
    for import in imports {
        out.push_str(&format!(
            "      '{}': (...args) => (host.{}?.['{}'] ?? (() => missing('{}', '{}')))(...args),\n",
            import.import_name,
            import.kind.namespace(),
            import.source_name,
            import.kind.label(),
            import.source_name
        ));
    }
    out.push_str("    },\n");
    out.push_str("  };\n");
    out.push_str("}\n\n");
    out.push_str("export async function instantiate(hostOrImports = {}) {\n");
    out.push_str("  const imports = hostOrImports['corvid:host'] ? hostOrImports : adaptImports(hostOrImports);\n");
    out.push_str("  const source = await WebAssembly.instantiateStreaming(fetch(WASM_URL), imports).catch(async () => {\n");
    out.push_str("    const bytes = await fetch(WASM_URL).then((r) => r.arrayBuffer());\n");
    out.push_str("    return WebAssembly.instantiate(bytes, imports);\n");
    out.push_str("  });\n");
    out.push_str("  const exports = source.instance.exports;\n");
    out.push_str("  return {\n");
    for agent in agents {
        let params = agent
            .params
            .iter()
            .map(|param| param.name.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    {}({}) {{\n", agent.name, params));
        match agent.return_ty {
            Type::Nothing => {
                out.push_str(&format!("      exports.{}({});\n", agent.name, params));
                out.push_str("      return undefined;\n");
            }
            Type::Bool => {
                out.push_str(&format!(
                    "      const result = exports.{}({});\n",
                    agent.name, params
                ));
                out.push_str(&format!(
                    "      return {};\n",
                    js_return_expr("result", &agent.return_ty)
                ));
            }
            _ => {
                out.push_str(&format!("      return exports.{}({});\n", agent.name, params));
            }
        }
        out.push_str("    },\n");
    }
    out.push_str("  };\n");
    out.push_str("}\n");
    Ok(out)
}

fn emit_ts_types(
    agents: &[&IrAgent],
    imports: &[WasmHostImport],
) -> Result<String, WasmCodegenError> {
    let mut out = String::new();
    out.push_str("// Auto-generated by Corvid. Do not edit.\n");
    out.push_str("export interface CorvidWasmHost {\n");
    out.push_str("  prompts?: {\n");
    for import in imports.iter().filter(|import| import.kind.namespace() == "prompts") {
        out.push_str(&format!("    '{}': {};\n", import.source_name, host_fn_type(import)?));
    }
    out.push_str("  };\n");
    out.push_str("  tools?: {\n");
    for import in imports.iter().filter(|import| import.kind.namespace() == "tools") {
        out.push_str(&format!("    '{}': {};\n", import.source_name, host_fn_type(import)?));
    }
    out.push_str("  };\n");
    out.push_str("  approvals?: {\n");
    for import in imports
        .iter()
        .filter(|import| import.kind.namespace() == "approvals")
    {
        out.push_str(&format!("    '{}': {};\n", import.source_name, host_fn_type(import)?));
    }
    out.push_str("  };\n");
    out.push_str("}\n\n");
    out.push_str("export interface CorvidWasmModule {\n");
    for agent in agents {
        let params = agent
            .params
            .iter()
            .map(|param| Ok(format!("{}: {}", param.name, ts_type(&param.ty)?)))
            .collect::<Result<Vec<_>, WasmCodegenError>>()?
            .join(", ");
        out.push_str(&format!(
            "  {}({}): {};\n",
            agent.name,
            params,
            ts_type(&agent.return_ty)?
        ));
    }
    out.push_str("}\n\n");
    out.push_str(
        "export function adaptImports(host?: CorvidWasmHost): WebAssembly.Imports;\n",
    );
    out.push_str(
        "export function instantiate(hostOrImports?: WebAssembly.Imports | CorvidWasmHost): Promise<CorvidWasmModule>;\n",
    );
    Ok(out)
}

fn host_fn_type(import: &WasmHostImport) -> Result<String, WasmCodegenError> {
    let params = import
        .params
        .iter()
        .map(|(name, ty)| Ok(format!("{name}: {}", ts_type(ty)?)))
        .collect::<Result<Vec<_>, WasmCodegenError>>()?
        .join(", ");
    Ok(format!("({params}) => {}", ts_type(&import.return_ty)?))
}

fn emit_manifest(
    module_name: &str,
    agents: &[&IrAgent],
    imports: &[WasmHostImport],
) -> Result<String, WasmCodegenError> {
    let exports = agents
        .iter()
        .map(|agent| {
            let params = agent
                .params
                .iter()
                .map(|param| WasmParam {
                    name: param.name.clone(),
                    ty: param.ty.display_name(),
                })
                .collect();
            WasmExport {
                name: agent.name.clone(),
                params,
                return_type: agent.return_ty.display_name(),
            }
        })
        .collect();
    let imports = imports
        .iter()
        .map(|import| WasmImport {
            kind: import.kind.label(),
            source_name: import.source_name.clone(),
            import_module: "corvid:host",
            import_name: import.import_name.clone(),
            params: import
                .params
                .iter()
                .map(|(name, ty)| WasmParam {
                    name: name.clone(),
                    ty: ty.display_name(),
                })
                .collect(),
            return_type: import.return_ty.display_name(),
        })
        .collect();
    let manifest = WasmManifest {
        schema_version: 1,
        module_name: module_name.to_string(),
        target: "wasm32-unknown-unknown",
        exports,
        imports,
        host_capability_abi: "corvid:host scalar imports v1",
        non_scope: vec![
            "replay trace recording in JS",
            "string and struct ABI",
            "provenance handles",
            "streaming host callbacks",
        ],
    };
    serde_json::to_string_pretty(&manifest)
        .map_err(|err| WasmCodegenError::unsupported(format!("serialize wasm manifest: {err}")))
}
