//! close-out benchmarks.
//!
//! Three suites:
//!
//! 1. Allocation throughput
//! 2. Cycle-collection throughput
//! 3. Verifier overhead (`corvid_gc_verify_mode = warn`)
//!
//! Methodology:
//!
//! - Criterion median + IQR; warm-up excluded by Criterion
//! - deterministic fixed-size workloads
//! - collector timing excludes graph-setup time via `iter_custom`
//! - VM and native collectors stay split because they are different
//! algorithms over different heaps use corvid_resolve::DefId;
use corvid_vm::{collect_cycles, StructValue, Value};
use criterion::{ criterion_group, criterion_main, BenchmarkId, Criterion, Throughput,
};
use std::hint::black_box;
use std::sync::OnceLock;
use std::time::{Duration, Instant}; const BOX_BATCH: usize = 20_000;
const STRING_BATCH: usize = 4_000;
const LIST_BATCH: usize = 512;
const LIST_STRING_LEN: usize = 32;
const PRIMITIVE_OPS: usize = 2_000_000;
const RC_OPS: usize = 1_000_000;
const COLD_CACHE_BYTES: usize = 16 * 1024 * 1024;
const COLD_CACHE_LINE: usize = 64; const CYCLE_SIZES: [usize; 4] = [10, 100, 1_000, 10_000]; #[repr(C)]
struct CorvidTypeinfo { size: u32, flags: u32, destroy_fn: Option<unsafe extern "C" fn(*mut u8)>, trace_fn: Option< unsafe extern "C" fn(*mut u8, Option<unsafe extern "C" fn(*mut u8, *mut u8)>, *mut u8,), >, weak_fn: Option<unsafe extern "C" fn(*mut u8)>, elem_typeinfo: *const CorvidTypeinfo, name: *const u8,
} #[repr(C)]
struct CorvidString { bytes_ptr: *const u8, length: i64,
} unsafe impl Sync for CorvidTypeinfo {}
unsafe impl Send for CorvidTypeinfo {} #[link(name = "corvid_c_runtime", kind = "static")]
extern "C" { fn corvid_alloc_typed(payload_bytes: i64, typeinfo: *const CorvidTypeinfo) -> *mut u8; fn corvid_retain(payload: *mut u8); fn corvid_release(payload: *mut u8); fn corvid_gc_from_roots(roots: *mut *mut u8, n_roots: usize); fn corvid_string_from_bytes(bytes: *const u8, length: i64) -> *mut u8; fn corvid_string_concat(a_payload: *mut u8, b_payload: *mut u8) -> *mut u8; fn corvid_destroy_list(payload: *mut u8); fn corvid_trace_list(payload: *mut u8, marker: Option<unsafe extern "C" fn(*mut u8, *mut u8)>, ctx: *mut u8,); fn corvid_weak_clear_self(payload: *mut u8); static corvid_typeinfo_String: CorvidTypeinfo; static mut corvid_gc_verify_mode: i32;
} unsafe extern "C" fn cell_trace(payload: *mut u8, marker: Option<unsafe extern "C" fn(*mut u8, *mut u8)>, ctx: *mut u8,) { let slots = payload as *mut *mut u8; for i in 0..2 { let ptr = *slots.add(i); if !ptr.is_null { if let Some(marker) = marker { marker(ptr, ctx); } } }
} unsafe extern "C" fn cell_destroy(payload: *mut u8) { let slots = payload as *mut *mut u8; for i in 0..2 { let ptr = *slots.add(i); if !ptr.is_null { corvid_release(ptr); } }
} static BOX_TYPEINFO: CorvidTypeinfo = CorvidTypeinfo { size: 8, flags: 0, destroy_fn: None, trace_fn: None, weak_fn: None, elem_typeinfo: std::ptr::null, name: std::ptr::null,
}; static CELL_TYPEINFO: CorvidTypeinfo = CorvidTypeinfo { size: 16, flags: 0x01, destroy_fn: Some(cell_destroy), trace_fn: Some(cell_trace), weak_fn: Some(corvid_weak_clear_self), elem_typeinfo: std::ptr::null, name: std::ptr::null,
}; fn list_string_typeinfo -> &'static CorvidTypeinfo { static LIST_STRING_TYPEINFO: OnceLock<CorvidTypeinfo> = OnceLock::new; LIST_STRING_TYPEINFO.get_or_init(|| unsafe { CorvidTypeinfo { size: 0, flags: 0, destroy_fn: Some(corvid_destroy_list), trace_fn: Some(corvid_trace_list), weak_fn: Some(corvid_weak_clear_self), elem_typeinfo: &corvid_typeinfo_String, name: std::ptr::null, } })
} struct VerifyModeGuard { prev: i32,
} impl VerifyModeGuard { unsafe fn new(mode: i32) -> Self { let prev = corvid_gc_verify_mode; corvid_gc_verify_mode = mode; Self { prev } }
} impl Drop for VerifyModeGuard { fn drop(&mut self) { unsafe { corvid_gc_verify_mode = self.prev; } }
} unsafe fn alloc_box_batch(count: usize) { let mut roots = Vec::with_capacity(count); for _ in 0..count { roots.push(corvid_alloc_typed(8, &BOX_TYPEINFO)); } for root in roots { corvid_release(root); }
} unsafe fn alloc_box_batch_with_gc(count: usize) { let mut roots = Vec::with_capacity(count); for _ in 0..count { roots.push(corvid_alloc_typed(8, &BOX_TYPEINFO)); } corvid_gc_from_roots(roots.as_mut_ptr, roots.len); for root in roots { corvid_release(root); }
} unsafe fn string_concat_batch(count: usize) { let left_bytes = b"corvid"; let right_bytes = b"memory"; let left = corvid_string_from_bytes(left_bytes.as_ptr as *const i8 as *const u8, left_bytes.len as i64); let right = corvid_string_from_bytes(right_bytes.as_ptr as *const i8 as *const u8, right_bytes.len as i64); let mut roots = Vec::with_capacity(count); let mut total_len = 0i64; for _ in 0..count { let value = corvid_string_concat(left, right); total_len += (*(value as *const CorvidString)).length; roots.push(value); } black_box(total_len); for root in roots { corvid_release(root); } corvid_release(left); corvid_release(right);
} unsafe fn string_concat_batch_with_gc(count: usize) { let left_bytes = b"corvid"; let right_bytes = b"memory"; let left = corvid_string_from_bytes(left_bytes.as_ptr as *const i8 as *const u8, left_bytes.len as i64); let right = corvid_string_from_bytes(right_bytes.as_ptr as *const i8 as *const u8, right_bytes.len as i64); let mut roots = Vec::with_capacity(count + 2); roots.push(left); roots.push(right); let mut total_len = 0i64; for _ in 0..count { let value = corvid_string_concat(left, right); total_len += (*(value as *const CorvidString)).length; roots.push(value); } black_box(total_len); corvid_gc_from_roots(roots.as_mut_ptr, roots.len); for root in roots { corvid_release(root); }
} unsafe fn alloc_string_list(len: usize) -> *mut u8 { let payload = corvid_alloc_typed(((len + 1) * 8) as i64, list_string_typeinfo); let slots = payload as *mut i64; slots.write(len as i64); for i in 0..len { let text = format!("item{i}"); let string = corvid_string_from_bytes(text.as_ptr, text.len as i64); *slots.add(1 + i) = string as isize as i64; } payload
} unsafe fn list_string_batch(count: usize, list_len: usize) { let mut roots = Vec::with_capacity(count); let mut total_len = 0i64; for _ in 0..count { let list = alloc_string_list(list_len); let slots = list as *mut i64; let len = *slots as usize; for i in 0..len { let string = *slots.add(1 + i) as isize as *mut CorvidString; total_len += (*string).length; } roots.push(list); } black_box(total_len); for root in roots { corvid_release(root); }
} unsafe fn list_string_batch_with_gc(count: usize, list_len: usize) { let mut roots = Vec::with_capacity(count); let mut total_len = 0i64; for _ in 0..count { let list = alloc_string_list(list_len); let slots = list as *mut i64; let len = *slots as usize; for i in 0..len { let string = *slots.add(1 + i) as isize as *mut CorvidString; total_len += (*string).length; } roots.push(list); } black_box(total_len); corvid_gc_from_roots(roots.as_mut_ptr, roots.len); for root in roots { corvid_release(root); }
} fn primitive_control_batch(ops: usize) -> i64 { let mut total = 0i64; for i in 0..ops { total = total.wrapping_add((i as i64) ^ 0x5a5a); } total
} fn cold_cache_order -> &'static [usize] { static ORDER: OnceLock<Vec<usize>> = OnceLock::new; ORDER.get_or_init(|| { let lines = COLD_CACHE_BYTES / COLD_CACHE_LINE; let mut order: Vec<usize> = (0..lines).map(|i| i * COLD_CACHE_LINE).collect; let mut x: u64 = 0x9E37_79B9_7F4A_7C15; for i in (1..order.len).rev { x ^= x >> 12; x ^= x << 25; x ^= x >> 27; let j = (x.wrapping_mul(0x2545_F491_4F6C_DD1D) as usize) % (i + 1); order.swap(i, j); } order })
} fn cold_cache_buffer -> &'static [u8] { static BUFFER: OnceLock<Vec<u8>> = OnceLock::new; BUFFER.get_or_init(|| vec![0xA5; COLD_CACHE_BYTES])
} fn cold_cache_preload { let buffer = cold_cache_buffer; let mut sum = 0u64; for &idx in cold_cache_order { sum = sum.wrapping_add(buffer[idx] as u64); } black_box(sum);
} unsafe fn build_native_cycle(size: usize) { let mut nodes = Vec::with_capacity(size); for _ in 0..size { let node = corvid_alloc_typed(16, &CELL_TYPEINFO); let slots = node as *mut *mut u8; slots.write(std::ptr::null_mut); slots.add(1).write(std::ptr::null_mut); nodes.push(node); } for i in 0..size { let next = nodes[(i + 1) % size]; (nodes[i] as *mut *mut u8).write(next); }
} fn build_vm_cycle(size: usize) { let mut nodes = Vec::with_capacity(size); for i in 0..size { nodes.push(StructValue::new(DefId(i as u32), "Node", [])); } for i in 0..size { let next = nodes[(i + 1) % size].clone; nodes[i].set_field("next", Value::Struct(next)); } drop(nodes);
} fn timed_vm_cycle_collection(size: usize) -> Duration { build_vm_cycle(size); let start = Instant::now; let _ = collect_cycles; start.elapsed
} unsafe fn retain_only_batch(count: usize) { let payload = corvid_alloc_typed(8, &BOX_TYPEINFO); for _ in 0..count { corvid_retain(payload); } for _ in 0..=count { corvid_release(payload); }
} unsafe fn release_only_batch(count: usize) { let payload = corvid_alloc_typed(8, &BOX_TYPEINFO); for _ in 0..count { corvid_retain(payload); } for _ in 0..count { corvid_release(payload); } corvid_release(payload);
} unsafe fn retain_release_pair_batch(count: usize) { let payload = corvid_alloc_typed(8, &BOX_TYPEINFO); for _ in 0..count { corvid_retain(payload); corvid_release(payload); } corvid_release(payload);
} fn bench_allocation_throughput(c: &mut Criterion) { let mut group = c.benchmark_group("memory_alloc"); group.throughput(Throughput::Elements(BOX_BATCH as u64)); group.bench_function("tight_box_alloc", |b| { b.iter(|| unsafe { alloc_box_batch(black_box(BOX_BATCH)) }) }); group.bench_function("tight_box_alloc_cold_preload", |b| { b.iter_custom(|iters| { let mut total = Duration::ZERO; for _ in 0..iters { cold_cache_preload; let start = Instant::now; unsafe { alloc_box_batch(black_box(BOX_BATCH)) }; total += start.elapsed; } total }) }); group.throughput(Throughput::Elements((STRING_BATCH + 2) as u64)); group.bench_function("string_heavy_concat", |b| { b.iter(|| unsafe { string_concat_batch(black_box(STRING_BATCH)) }) }); let list_allocs = (LIST_BATCH * (LIST_STRING_LEN + 1)) as u64; group.throughput(Throughput::Elements(list_allocs)); group.bench_function("list_heavy_strings", |b| { b.iter(|| unsafe { list_string_batch(black_box(LIST_BATCH), black_box(LIST_STRING_LEN)) }) }); group.throughput(Throughput::Elements(PRIMITIVE_OPS as u64)); group.bench_function("primitive_control", |b| { b.iter(|| black_box(primitive_control_batch(black_box(PRIMITIVE_OPS)))) }); group.throughput(Throughput::Elements(RC_OPS as u64)); group.bench_with_input(BenchmarkId::new("rc_ops_isolated", "retain"), &RC_OPS, |b, &count| { b.iter(|| unsafe { retain_only_batch(black_box(count)) }) }); group.bench_with_input(BenchmarkId::new("rc_ops_isolated", "release"), &RC_OPS, |b, &count| { b.iter(|| unsafe { release_only_batch(black_box(count)) }) }); group.bench_with_input(BenchmarkId::new("rc_ops_isolated", "retain_release_pair"), &RC_OPS, |b, &count| b.iter(|| unsafe { retain_release_pair_batch(black_box(count)) }),); group.finish;
} fn bench_verifier_overhead(c: &mut Criterion) { let mut group = c.benchmark_group("memory_verify"); for &(label, mode) in &[("off", 0), ("warn", 1)] { group.throughput(Throughput::Elements(BOX_BATCH as u64)); group.bench_with_input(BenchmarkId::new("tight_box_alloc", label), &mode, |b, &mode| { let _guard = unsafe { VerifyModeGuard::new(mode) }; b.iter(|| unsafe { alloc_box_batch_with_gc(black_box(BOX_BATCH)) }); }); group.throughput(Throughput::Elements((STRING_BATCH + 2) as u64)); group.bench_with_input(BenchmarkId::new("string_heavy_concat", label), &mode, |b, &mode| { let _guard = unsafe { VerifyModeGuard::new(mode) }; b.iter(|| unsafe { string_concat_batch_with_gc(black_box(STRING_BATCH)) }); }); let list_allocs = (LIST_BATCH * (LIST_STRING_LEN + 1)) as u64; group.throughput(Throughput::Elements(list_allocs)); group.bench_with_input(BenchmarkId::new("list_heavy_strings", label), &mode, |b, &mode| { let _guard = unsafe { VerifyModeGuard::new(mode) }; b.iter(|| unsafe { list_string_batch_with_gc(black_box(LIST_BATCH), black_box(LIST_STRING_LEN)) }); }); } group.finish;
} fn bench_cycle_collectors(c: &mut Criterion) { std::env::set_var("CORVID_VM_GC_TRIGGER", "0"); let mut group = c.benchmark_group("memory_collect"); for &size in &CYCLE_SIZES { group.throughput(Throughput::Elements(size as u64)); group.bench_with_input(BenchmarkId::new("native_mark_sweep", size), &size, |b, &size| { b.iter_custom(|iters| { let mut total = Duration::ZERO; for _ in 0..iters { unsafe { build_native_cycle(size) }; let mut roots: [*mut u8; 0] = []; let start = Instant::now; unsafe { corvid_gc_from_roots(roots.as_mut_ptr, 0) }; total += start.elapsed; } total }); }); group.throughput(Throughput::Elements(size as u64)); group.bench_with_input(BenchmarkId::new("vm_bacon_rajan", size), &size, |b, &size| { b.iter_custom(|iters| { let mut total = Duration::ZERO; for _ in 0..iters { total += timed_vm_cycle_collection(size); } total }); }); } group.finish;
} criterion_group!(memory_runtime, bench_allocation_throughput, bench_cycle_collectors, bench_verifier_overhead,);
criterion_main!(memory_runtime);
