// Generated by Corvid -- DO NOT EDIT.
// Phase 22 slices 22-A/22-C.
//
// String ABI ownership for this header:
//   * inbound `const char*` parameters are UTF-8, null-terminated, caller-owned
//   * outbound `const char*` returns are UTF-8, null-terminated, Corvid-owned
//   * release returned agent strings with `corvid_free_string(...)`
//   * release `corvid_call_agent` JSON payloads with `corvid_free_result(...)`
//   * grounded-return handles are runtime attestations; release them with `corvid_grounded_release(...)`

//   * observation handles are runtime attestations; release them with `corvid_observation_release(...)`

#ifndef CORVID_CLASSIFY_H
#define CORVID_CLASSIFY_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    CORVID_TRUST_AUTONOMOUS = 0,
    CORVID_TRUST_HUMAN_REQUIRED = 1,
    CORVID_TRUST_SECURITY_REVIEW = 2,
} CorvidTrustTier;

typedef struct {
    const char* name;
    const char* symbol;
    const char* source_file;
    uint32_t source_line;
    uint8_t trust_tier;
    double cost_bound_usd;
    uint8_t reversible;
    uint8_t latency_instant;
    uint8_t replayable;
    uint8_t deterministic;
    uint8_t dangerous;
    uint8_t pub_extern_c;
    uint8_t requires_approval;
    uint32_t grounded_source_count;
    uint32_t param_count;
} CorvidAgentHandle;

typedef enum {
    CORVID_CALL_OK = 0,
    CORVID_CALL_AGENT_NOT_FOUND = 1,
    CORVID_CALL_BAD_ARGS = 2,
    CORVID_CALL_UNSUPPORTED_SIG = 3,
    CORVID_CALL_APPROVAL_REQUIRED = 4,
    CORVID_CALL_BUDGET_EXCEEDED = 5,
    CORVID_CALL_RUNTIME_ERROR = 6,
} CorvidCallStatus;

typedef struct {
    const char* site_name;
    const char* predicate_json;
    const char* args_json;
    const char* rationale_prompt;
} CorvidApprovalRequired;

typedef enum {
    CORVID_PREFLIGHT_OK = 0,
    CORVID_PREFLIGHT_AGENT_NOT_FOUND = 1,
    CORVID_PREFLIGHT_BAD_ARGS = 2,
    CORVID_PREFLIGHT_UNSUPPORTED_SIG = 3,
} CorvidPreFlightStatus;

typedef enum {
    CORVID_FIND_AGENTS_OK = 0,
    CORVID_FIND_AGENTS_BAD_JSON = 1,
    CORVID_FIND_AGENTS_UNKNOWN_DIMENSION = 2,
    CORVID_FIND_AGENTS_OP_MISMATCH = 3,
} CorvidFindAgentsStatus;

typedef struct {
    CorvidPreFlightStatus status;
    double cost_bound_usd;
    uint8_t requires_approval;
    const char* effect_row_json;
    const char* grounded_source_set_json;
    const char* bad_args_message;
} CorvidPreFlight;

typedef struct {
    CorvidFindAgentsStatus status;
    size_t matched_count;
    const char* error_message;
} CorvidFindAgentsResult;

typedef enum {
    CORVID_APPROVAL_ACCEPT = 0,
    CORVID_APPROVAL_REJECT = 1,
} CorvidApprovalDecision;

typedef CorvidApprovalDecision (*CorvidApproverFn)(
    const CorvidApprovalRequired* request,
    void* user_data);

typedef enum {
    CORVID_APPROVER_OK = 0,
    CORVID_APPROVER_IO_ERROR = 1,
    CORVID_APPROVER_COMPILE_ERROR = 2,
    CORVID_APPROVER_MISSING_AGENT = 3,
    CORVID_APPROVER_BAD_SIGNATURE = 4,
    CORVID_APPROVER_UNSAFE = 5,
    CORVID_APPROVER_OVER_BUDGET = 6,
} CorvidApproverLoadStatus;

typedef enum {
    CORVID_PREDICATE_OK = 0,
    CORVID_PREDICATE_BAD_ARGS = 1,
    CORVID_PREDICATE_SITE_NOT_FOUND = 2,
    CORVID_PREDICATE_UNEVALUABLE = 3,
} CorvidPredicateStatus;

typedef struct {
    CorvidPredicateStatus status;
    uint8_t requires_approval;
    const char* bad_args_message;
} CorvidPredicateResult;

typedef enum {
    CORVID_HOST_EVENT_OK = 0,
    CORVID_HOST_EVENT_BAD_JSON = 1,
    CORVID_HOST_EVENT_TRACE_DISABLED = 2,
    CORVID_HOST_EVENT_RUNTIME_ERROR = 3,
} CorvidHostEventStatus;

#define CORVID_NULL_GROUNDED_HANDLE ((uint64_t)0)

#define CORVID_NULL_OBSERVATION_HANDLE ((uint64_t)0)

const char* corvid_abi_descriptor_json(size_t* out_len);
void corvid_abi_descriptor_hash(uint8_t out_hash[32]);
int corvid_abi_verify(const uint8_t expected[32]);
size_t corvid_list_agents(CorvidAgentHandle* out, size_t capacity);
CorvidFindAgentsResult corvid_find_agents_where(
    const char* filter_json,
    size_t filter_len,
    size_t* out_indices,
    size_t out_cap);
const char* corvid_agent_signature_json(const char* agent_name, size_t* out_len);
CorvidPreFlight corvid_pre_flight(const char* agent_name, const char* args_json, size_t args_len);
CorvidCallStatus corvid_call_agent(
    const char* agent_name,
    const char* args_json,
    size_t args_len,
    char** out_result,
    size_t* out_result_len,
    uint64_t* out_observation_handle,
    CorvidApprovalRequired* out_approval);
void corvid_free_result(char* result);
void corvid_register_approver(CorvidApproverFn fn, void* user_data);
CorvidApproverLoadStatus corvid_register_approver_from_source(
    const char* source_path,
    double max_budget_usd_per_call,
    char** out_error_message);
void corvid_clear_approver(void);
bool corvid_mark_preapproved_request(
    const char* site_name,
    const char* args_json,
    size_t args_len);
const char* corvid_approval_predicate_json(const char* site_name, size_t* out_len);
CorvidPredicateResult corvid_evaluate_approval_predicate(
    const char* site_name,
    const char* args_json,
    size_t args_len);
int32_t corvid_grounded_sources(uint64_t handle, const char** out, size_t capacity);
double corvid_grounded_confidence(uint64_t handle);
void corvid_grounded_release(uint64_t handle);
double corvid_observation_cost_usd(uint64_t handle);
uint64_t corvid_observation_latency_ms(uint64_t handle);
uint64_t corvid_observation_tokens_in(uint64_t handle);
uint64_t corvid_observation_tokens_out(uint64_t handle);
bool corvid_observation_exceeded_bound(uint64_t handle);
void corvid_observation_release(uint64_t handle);
CorvidHostEventStatus corvid_record_host_event(
    const char* name,
    const char* payload_json,
    size_t payload_len);
void corvid_free_string(const char* value);

// agent classify(text: String) -> String
const char* classify(const char* text, uint64_t* out_observation_handle);

// agent issue_tag(tag: String) -> String
const char* issue_tag(const char* tag, uint64_t* out_observation_handle);

// agent grounded_tag(tag: String) -> Grounded<String>
const char* grounded_tag(const char* tag, uint64_t* out_grounded_handle, uint64_t* out_observation_handle);

#ifdef __cplusplus
}
#endif

#endif // CORVID_CLASSIFY_H
