# @generated by corvid bind python.
# descriptor sha256: b0a8fd4e20c07d83faf63179bbd39053c8eaa3496d6a9e2ea53a9d5750b0c6e5
# corvid-bind version: 0.0.1
# descriptor generated_at: 1970-01-01T00:00:00Z
from __future__ import annotations

import ctypes
import json
from typing import ClassVar, Protocol

from .common import (
    ApprovalDecision,
    ApprovalDeniedError,
    Approver,
    CallError,
    Client,
    CorvidError,
    Grounded,
    Observation,
    TrustTier,
    _decode,
)
from .types import *

class GroundedTag:
    NAME: ClassVar[str] = 'grounded_tag'
    SYMBOL: ClassVar[str] = 'grounded_tag'
    TRUST_TIER: ClassVar[TrustTier] = TrustTier.AUTONOMOUS
    COST_BOUND_USD: ClassVar[float | None] = 0.01
    IS_DANGEROUS: ClassVar[bool] = False

class GroundedTagApi(Protocol):
    def grounded_tag(self, tag: str) -> tuple[Grounded[str], Observation]: ...

def _grounded_tag(client: Client, tag: str) -> tuple[Grounded[str], Observation]:
    fn = client.library.grounded_tag
    fn.argtypes = [
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_uint64),
        ctypes.POINTER(ctypes.c_uint64),
    ]
    fn.restype = ctypes.c_void_p
    arg_0 = tag.encode('utf-8')
    grounded_handle = ctypes.c_uint64()
    observation_handle = ctypes.c_uint64()
    value = fn(arg_0, ctypes.byref(grounded_handle), ctypes.byref(observation_handle))
    free = client.library.corvid_free_string
    free.argtypes = [ctypes.c_void_p]
    free.restype = None
    payload = ctypes.string_at(value).decode('utf-8')
    free(value)
    return Grounded(client.library, payload, grounded_handle.value, "corvid_grounded_release"), Observation(client.library, observation_handle.value, 'corvid_observation_release')

setattr(Client, 'grounded_tag', _grounded_tag)
