// @generated by corvid bind rust.
use std::ffi::c_char;

use libloading::Symbol;
use serde_json::json;

use crate::common::{
    read_c_string_lossy, Client, CorvidAgentHandleRaw, CorvidError, CorvidFindAgentsResultRaw,
    CorvidResult, TrustTier, CORVID_FIND_AGENTS_OK,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FindAgentsStatus {
    Ok,
    BadJson,
    UnknownDimension,
    OpMismatch,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reversibility {
    Reversible,
    Irreversible,
}

#[derive(Debug, Clone)]
pub struct AgentInfo {
    pub name: String,
    pub symbol: String,
    pub source_file: String,
    pub source_line: u32,
    pub trust_tier: TrustTier,
    pub cost_bound_usd: Option<f64>,
    pub reversible: Option<Reversibility>,
    pub replayable: bool,
    pub deterministic: bool,
    pub dangerous: bool,
    pub pub_extern_c: bool,
    pub requires_approval: bool,
    pub grounded_source_count: u32,
    pub param_count: u32,
}

pub struct Catalog<'a> {
    client: &'a Client,
}

pub struct CatalogQuery<'a> {
    client: &'a Client,
    clauses: Vec<serde_json::Value>,
}

impl<'a> Catalog<'a> {
    pub(crate) fn new(client: &'a Client) -> Self {
        Self { client }
    }

    pub fn query(&self) -> CatalogQuery<'a> {
        CatalogQuery {
            client: self.client,
            clauses: Vec::new(),
        }
    }

    pub fn where_trust_tier_le(&self, tier: TrustTier) -> CatalogQuery<'a> {
        self.query().where_trust_tier_le(tier)
    }

    pub fn where_cost_bound_usd_le(&self, usd: f64) -> CatalogQuery<'a> {
        self.query().where_cost_bound_usd_le(usd)
    }

    pub fn not_dangerous(&self) -> CatalogQuery<'a> {
        self.query().not_dangerous()
    }
}

impl<'a> CatalogQuery<'a> {
    fn push_clause(mut self, clause: serde_json::Value) -> Self {
        self.clauses.push(clause);
        self
    }

    pub fn where_trust_tier_le(self, tier: TrustTier) -> Self {
        let value = match tier {
            TrustTier::Autonomous => "autonomous",
            TrustTier::HumanRequired => "human_required",
            TrustTier::SecurityReview => "security_review",
        };
        self.push_clause(json!({"dim":"trust_tier","op":"le","value":value}))
    }

    pub fn where_cost_bound_usd_le(self, usd: f64) -> Self {
        self.push_clause(json!({"dim":"cost_bound_usd","op":"le","value":usd}))
    }

    pub fn where_latency_p99_ms_le(self, ms: f64) -> Self {
        self.push_clause(json!({"dim":"latency_p99_ms","op":"le","value":ms}))
    }

    pub fn not_dangerous(self) -> Self {
        self.push_clause(json!({"dim":"dangerous","op":"eq","value":false}))
    }

    pub fn replayable(self) -> Self {
        self.push_clause(json!({"dim":"replayable","op":"eq","value":true}))
    }

    pub fn deterministic(self) -> Self {
        self.push_clause(json!({"dim":"deterministic","op":"eq","value":true}))
    }

    pub fn find(self) -> CorvidResult<Vec<AgentInfo>> {
        let filter = if self.clauses.len() == 1 {
            self.clauses.into_iter().next().unwrap()
        } else {
            json!({ "all": self.clauses })
        };
        let filter_json = serde_json::to_string(&filter)
            .map_err(|err| CorvidError::Decode(err.to_string()))?;
        unsafe {
            let find: Symbol<
                unsafe extern "C" fn(*const c_char, usize, *mut usize, usize) -> CorvidFindAgentsResultRaw,
            > = self
                .client
                .library
                .get(b"corvid_find_agents_where")
                .map_err(|err| CorvidError::Load(err.to_string()))?;
            let list: Symbol<unsafe extern "C" fn(*mut CorvidAgentHandleRaw, usize) -> usize> = self
                .client
                .library
                .get(b"corvid_list_agents")
                .map_err(|err| CorvidError::Load(err.to_string()))?;

            let filter_json = std::ffi::CString::new(filter_json)
                .map_err(|err| CorvidError::BadArgs(err.to_string()))?;
            let raw = find(filter_json.as_ptr(), filter_json.as_bytes().len(), std::ptr::null_mut(), 0);
        if raw.status != CORVID_FIND_AGENTS_OK {
                return Err(CorvidError::Runtime(read_c_string_lossy(raw.error_message)));
            }
            let mut matched = vec![0usize; raw.matched_count];
            let raw = find(
                filter_json.as_ptr(),
                filter_json.as_bytes().len(),
                matched.as_mut_ptr(),
                matched.len(),
            );
            if raw.status != CORVID_FIND_AGENTS_OK {
                return Err(CorvidError::Runtime(read_c_string_lossy(raw.error_message)));
            }
            let total = list(std::ptr::null_mut(), 0);
            let mut handles = vec![
                CorvidAgentHandleRaw {
                    name: std::ptr::null(),
                    symbol: std::ptr::null(),
                    source_file: std::ptr::null(),
                    source_line: 0,
                    trust_tier: 0,
                    cost_bound_usd: 0.0,
                    reversible: 0,
                    latency_instant: 0,
                    replayable: 0,
                    deterministic: 0,
                    dangerous: 0,
                    pub_extern_c: 0,
                    requires_approval: 0,
                    grounded_source_count: 0,
                    param_count: 0,
                };
                total
            ];
            list(handles.as_mut_ptr(), handles.len());
            Ok(matched
                .into_iter()
                .filter_map(|index| handles.get(index).copied())
                .map(AgentInfo::from_raw)
                .collect())
        }
    }
}

impl AgentInfo {
    fn from_raw(raw: CorvidAgentHandleRaw) -> Self {
        Self {
            name: read_c_string_lossy(raw.name),
            symbol: read_c_string_lossy(raw.symbol),
            source_file: read_c_string_lossy(raw.source_file),
            source_line: raw.source_line,
            trust_tier: match raw.trust_tier {
                1 => TrustTier::HumanRequired,
                2 => TrustTier::SecurityReview,
                _ => TrustTier::Autonomous,
            },
            cost_bound_usd: if raw.cost_bound_usd.is_finite() {
                Some(raw.cost_bound_usd)
            } else {
                None
            },
            reversible: match raw.reversible {
                0 => Some(Reversibility::Reversible),
                1 => Some(Reversibility::Irreversible),
                _ => None,
            },
            replayable: raw.replayable != 0,
            deterministic: raw.deterministic != 0,
            dangerous: raw.dangerous != 0,
            pub_extern_c: raw.pub_extern_c != 0,
            requires_approval: raw.requires_approval != 0,
            grounded_source_count: raw.grounded_source_count,
            param_count: raw.param_count,
        }
    }
}
