# @generated by corvid bind python.
# descriptor sha256: b0a8fd4e20c07d83faf63179bbd39053c8eaa3496d6a9e2ea53a9d5750b0c6e5
# corvid-bind version: 0.0.1
# descriptor generated_at: 1970-01-01T00:00:00Z
from __future__ import annotations

import ctypes
import json
from typing import ClassVar, Protocol

from .common import (
    ApprovalDecision,
    ApprovalDeniedError,
    Approver,
    CallError,
    Client,
    CorvidError,
    Grounded,
    Observation,
    TrustTier,
    _decode,
)
from .types import *

class IssueTag:
    NAME: ClassVar[str] = 'issue_tag'
    SYMBOL: ClassVar[str] = 'issue_tag'
    TRUST_TIER: ClassVar[TrustTier] = TrustTier.HUMAN_REQUIRED
    COST_BOUND_USD: ClassVar[float | None] = 0.02
    IS_DANGEROUS: ClassVar[bool] = True

class IssueTagApi(Protocol):
    def issue_tag(self, tag: str, *, approver: Approver) -> tuple[str, Observation]: ...

def _issue_tag(client: Client, tag: str, approver: Approver) -> tuple[str, Observation]:
    args_json = json.dumps([
        tag,
    ])
    completed, payload, observation, request = client._probe_json_agent('issue_tag', args_json)
    if completed:
        return payload, observation
    assert request is not None
    decision = approver.decide(request)
    if decision == ApprovalDecision.REJECT:
        raise ApprovalDeniedError(request)
    client._mark_preapproved_request(request.site_name, request.args_json)
    fn = client.library.issue_tag
    fn.argtypes = [
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_uint64),
    ]
    fn.restype = ctypes.c_void_p
    arg_0 = tag.encode('utf-8')
    observation_handle = ctypes.c_uint64()
    value = fn(arg_0, ctypes.byref(observation_handle))
    free = client.library.corvid_free_string
    free.argtypes = [ctypes.c_void_p]
    free.restype = None
    payload = ctypes.string_at(value).decode('utf-8')
    free(value)
    return payload, Observation(client.library, observation_handle.value, 'corvid_observation_release')

setattr(Client, 'issue_tag', _issue_tag)
