# @generated by corvid bind python.
# descriptor sha256: a4cf8eb8bbed8655b4aa52860f4f7105e7ba60dacfd96c228a474607173134ae
# corvid-bind version: 0.0.1
# descriptor generated_at: 1970-01-01T00:00:00Z
from __future__ import annotations

import ctypes
import json
from typing import ClassVar, Protocol

from .common import (
    ApprovalDecision,
    ApprovalDeniedError,
    Approver,
    CallError,
    Client,
    CorvidError,
    Grounded,
    Observation,
    TrustTier,
    _decode,
)
from .types import *

class Classify:
    NAME: ClassVar[str] = 'classify'
    SYMBOL: ClassVar[str] = 'classify'
    TRUST_TIER: ClassVar[TrustTier] = TrustTier.AUTONOMOUS
    COST_BOUND_USD: ClassVar[float | None] = 0.01
    IS_DANGEROUS: ClassVar[bool] = False

class ClassifyApi(Protocol):
    def classify(self, text: str) -> tuple[str, Observation]: ...

def _classify(client: Client, text: str) -> tuple[str, Observation]:
    fn = client.library.classify
    fn.argtypes = [
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_uint64),
    ]
    fn.restype = ctypes.c_void_p
    arg_0 = text.encode('utf-8')
    observation_handle = ctypes.c_uint64()
    value = fn(arg_0, ctypes.byref(observation_handle))
    free = client.library.corvid_free_string
    free.argtypes = [ctypes.c_void_p]
    free.restype = None
    payload = ctypes.string_at(value).decode('utf-8')
    free(value)
    return payload, Observation(client.library, observation_handle.value, 'corvid_observation_release')

setattr(Client, 'classify', _classify)
