"""Replay-determinism rate orchestrator.

Reads each stack's `_summary.json` under `runs/<stack>/` and composes
a drift-gated `RESULTS.md`. Stacks without a `_summary.json` are
reported as `bounty-open`; the headline reflects partial coverage
explicitly rather than fabricating numbers.

Usage:
    python benches/moat/replay_determinism/runner/run.py \\
        --runs-dir benches/moat/replay_determinism/runs \\
        --out      benches/moat/replay_determinism/RESULTS.md
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


STACKS = [
    ("corvid", "Corvid (`cargo run -p refund_bot_demo`)"),
    ("python", "Python (LangChain + LangSmith)"),
    ("typescript", "TypeScript (Vercel AI SDK + OTEL)"),
]


@dataclass
class StackResult:
    stack: str
    label: str
    status: str  # "ran" | "bounty-open"
    n: int | None = None
    byte_identical_pairs: int | None = None
    total_pairs: int | None = None
    rate: float | None = None
    first_diverging_pair: dict | None = None


def load_stack(runs_dir: Path, stack: str, label: str) -> StackResult:
    summary_path = runs_dir / stack / "_summary.json"
    if not summary_path.exists():
        return StackResult(stack=stack, label=label, status="bounty-open")
    data = json.loads(summary_path.read_text(encoding="utf-8"))
    if data.get("stack") != stack:
        raise SystemExit(
            f"{summary_path} stack field is {data.get('stack')!r}, "
            f"expected {stack!r}"
        )
    return StackResult(
        stack=stack,
        label=label,
        status="ran",
        n=int(data["n"]),
        byte_identical_pairs=int(data["byte_identical_pairs"]),
        total_pairs=int(data["total_pairs"]),
        rate=float(data["determinism_rate"]),
        first_diverging_pair=data.get("first_diverging_pair"),
    )


def render_results_md(results: list[StackResult]) -> str:
    out: list[str] = []
    out.append("# Replay determinism rate — published results\n")
    out.append(
        "> Auto-generated by "
        "`benches/moat/replay_determinism/runner/run.py`. "
        "Do not hand-edit. Re-run the runner after adding or "
        "modifying stack runners.\n"
    )

    out.append("## Headline numbers\n")
    for r in results:
        if r.status == "ran":
            out.append(
                f"- {r.label}: "
                f"**{r.byte_identical_pairs}/{r.total_pairs} byte-identical pairs** "
                f"(rate = {r.rate:.3f}, N = {r.n})"
            )
        else:
            out.append(f"- {r.label}: **bounty-open** (no `_summary.json`)")
    out.append("")

    out.append("## Per-stack verdicts\n")
    out.append("| Stack | N | Identical pairs | Total pairs | Rate | Status |")
    out.append("|-------|---|-----------------|-------------|------|--------|")
    for r in results:
        if r.status == "ran":
            out.append(
                f"| `{r.stack}` | {r.n} | {r.byte_identical_pairs} "
                f"| {r.total_pairs} | {r.rate:.3f} | ran |"
            )
        else:
            out.append(
                f"| `{r.stack}` | — | — | — | — | bounty-open |"
            )

    diverging = [
        r for r in results if r.status == "ran" and r.first_diverging_pair
    ]
    if diverging:
        out.append("\n## First diverging pair (per stack)\n")
        for r in diverging:
            d = r.first_diverging_pair or {}
            out.append(
                f"- `{r.stack}`: runs `{d.get('run_a')}` vs `{d.get('run_b')}` "
                f"diverge at line {d.get('first_diverging_line')}"
            )

    out.append("\n## Methodology\n")
    out.append(
        "See `benches/moat/replay_determinism/README.md` for the run "
        "layout, normalization rules, and bounty window. The runner is "
        "non-judgmental — it reads each stack's `_summary.json` and "
        "renders the headline. Each stack's runner is responsible for "
        "running N times, applying its documented normalization, and "
        "writing the summary."
    )

    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs-dir", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    if not args.runs_dir.is_dir():
        raise SystemExit(f"runs dir {args.runs_dir} does not exist")

    results = [load_stack(args.runs_dir, s, l) for s, l in STACKS]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_results_md(results), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
