// @generated by corvid bind rust.
// descriptor sha256: b0a8fd4e20c07d83faf63179bbd39053c8eaa3496d6a9e2ea53a9d5750b0c6e5
// corvid-bind version: 0.0.1
// descriptor generated_at: 1970-01-01T00:00:00Z
use std::ffi::CString;

use libloading::Symbol;
use serde_json::json;

use crate::common::{
    take_owned_c_string, ApprovalDecision, Approver, CallAttempt, CallStatus, Client,
    CorvidError, CorvidResult, Grounded, Observation, TrustTier,
};
use crate::types::*;

pub struct Classify;

impl Classify {
    pub const NAME: &str = "classify";
    pub const SYMBOL: &str = "classify";
    pub const TRUST_TIER: TrustTier = TrustTier::Autonomous;
    pub const COST_BOUND_USD: Option<f64> = Some(0.01);
    pub const IS_DANGEROUS: bool = false;
    pub const RETURNS_GROUNDED: bool = false;
}

pub trait ClassifyApi {
    fn classify(&self, text: &str) -> CorvidResult<(String, Observation)>;
}

impl ClassifyApi for Client {
    fn classify(&self, text: &str) -> CorvidResult<(String, Observation)> {
        let arg_0 = CString::new(text).map_err(|err| CorvidError::BadArgs(err.to_string()))?;
        unsafe {
            let symbol: Symbol<unsafe extern "C" fn(*const std::ffi::c_char, *mut u64) -> *const std::ffi::c_char> = self.library.get(b"classify").map_err(|err| CorvidError::Load(err.to_string()))?;
            let mut observation_handle = 0u64;
            let value = symbol(arg_0.as_ptr(), &mut observation_handle);
            let payload = take_owned_c_string(&self.library, value, "corvid_free_string")?;
            Ok((payload, Observation::new(self.library.clone(), observation_handle, "corvid_observation_release")))
        }
    }
}
