//! Per-agent module emission — Phase 20j-A12 commit 5.
//!
//! [`render_agent_module`] generates one `src/<agent>.rs` per
//! user-defined agent. The body shape depends on the agent's
//! danger surface:
//!
//! - **Dangerous agents** (must hold an approve token at the
//!   call site) emit a body that constructs an
//!   `ApprovalRequest`, hands it to the host's approver, and
//!   refuses the call if the approver returns `Deny`.
//! - **Direct (non-dangerous) agents** emit a body that
//!   immediately invokes the C-ABI symbol with the typed
//!   args + maps the FFI return into the public Rust type.
//!
//! All ownership/grounding/danger detection lives in the
//! `crate::*` predicates pulled in below.

use std::fmt::Write as _;

use anyhow::Result;

use crate::{
    effective_param_ownership, effective_return_ownership, grounded_inner_kind, pascal_case,
    returns_grounded, rust_c_abi_param_type, rust_c_abi_return_type, rust_f64_literal,
    rust_public_param_type, rust_public_type, rust_string_literal, snake_case, BindingContext,
};

pub(super) fn render_agent_module(context: &BindingContext, agent: &corvid_abi::AbiAgent) -> Result<String> {
    let marker = pascal_case(&agent.name);
    let api_trait = format!("{marker}Api");
    let method_name = snake_case(&agent.name);
    let return_type = if returns_grounded(&agent.return_type) {
        format!(
            "Grounded<{}>",
            rust_public_type(
                grounded_inner(agent.return_type()).unwrap_or(&agent.return_type)
            )
        )
    } else {
        rust_public_type(&agent.return_type)
    };

    let mut out = String::new();
    out.push_str("// @generated by corvid bind rust.\n");
    out.push_str(&format!(
        "// descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("// corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "// descriptor generated_at: {}\n",
        context.abi.generated_at
    ));
    out.push_str("use std::ffi::CString;\n\n");
    out.push_str("use libloading::Symbol;\n");
    out.push_str("use serde_json::json;\n\n");
    out.push_str("use crate::common::{\n");
    out.push_str("    take_owned_c_string, ApprovalDecision, Approver, CallAttempt, CallStatus, Client,\n");
    out.push_str("    CorvidError, CorvidResult, Grounded, Observation, TrustTier,\n");
    out.push_str("};\n");
    out.push_str("use crate::types::*;\n\n");
    out.push_str(&format!("pub struct {marker};\n\n"));
    out.push_str(&format!("impl {marker} {{\n"));
    out.push_str(&format!(
        "    pub const NAME: &str = {};\n",
        rust_string_literal(&agent.name)
    ));
    out.push_str(&format!(
        "    pub const SYMBOL: &str = {};\n",
        rust_string_literal(&agent.symbol)
    ));
    out.push_str(&format!(
        "    pub const TRUST_TIER: TrustTier = TrustTier::{};\n",
        match agent.abi_effect_trust_tier().as_deref() {
            Some("human_required") => "HumanRequired",
            Some("security_review") => "SecurityReview",
            _ => "Autonomous",
        }
    ));
    if let Some(budget) = &agent.budget {
        out.push_str(&format!(
            "    pub const COST_BOUND_USD: Option<f64> = Some({});\n",
            rust_f64_literal(budget.usd_per_call)
        ));
    } else {
        out.push_str("    pub const COST_BOUND_USD: Option<f64> = None;\n");
    }
    out.push_str(&format!(
        "    pub const IS_DANGEROUS: bool = {};\n",
        if agent.attributes.dangerous { "true" } else { "false" }
    ));
    out.push_str(&format!(
        "    pub const RETURNS_GROUNDED: bool = {};\n",
        if returns_grounded(&agent.return_type) { "true" } else { "false" }
    ));
    out.push_str("}\n\n");

    let generics = render_method_generics(agent);
    out.push_str(&format!("pub trait {api_trait} {{\n"));
    out.push_str(&format!(
        "    fn {method_name}{generics}(&self{sig}) -> CorvidResult<({return_type}, Observation)>;\n",
        generics = generics,
        sig = render_trait_signature_params(agent)
    ));
    out.push_str("}\n\n");
    out.push_str(&format!("impl {api_trait} for Client {{\n"));
    out.push_str(&format!(
        "    fn {method_name}{generics}(&self{sig}) -> CorvidResult<({return_type}, Observation)> {{\n",
        generics = generics,
        sig = render_trait_signature_params(agent)
    ));
    if agent.attributes.dangerous {
        out.push_str(&render_dangerous_agent_body(agent)?);
    } else {
        out.push_str(&render_direct_agent_body(agent)?);
    }
    out.push_str("    }\n");
    out.push_str("}\n");

    Ok(out)
}

trait AbiAgentExt {
    fn abi_effect_trust_tier(&self) -> Option<String>;
    fn return_type(&self) -> &corvid_abi::TypeDescription;
}

impl AbiAgentExt for corvid_abi::AbiAgent {
    fn abi_effect_trust_tier(&self) -> Option<String> {
        self.effects.trust_tier.clone()
    }

    fn return_type(&self) -> &corvid_abi::TypeDescription {
        &self.return_type
    }
}

fn grounded_inner(ty: &corvid_abi::TypeDescription) -> Option<&corvid_abi::TypeDescription> {
    match ty {
        corvid_abi::TypeDescription::Grounded { grounded } => Some(grounded.inner.as_ref()),
        _ => None,
    }
}

fn render_trait_signature_params(agent: &corvid_abi::AbiAgent) -> String {
    let mut out = String::new();
    for param in &agent.params {
        out.push_str(", ");
        out.push_str(&snake_case(&param.name));
        out.push_str(": ");
        out.push_str(&rust_public_param_type(param));
    }
    if agent.attributes.dangerous {
        out.push_str(", approver: &dyn Approver");
    }
    out
}

fn render_method_generics(agent: &corvid_abi::AbiAgent) -> String {
    let mut lifetimes = Vec::new();
    for param in &agent.params {
        let ownership = effective_param_ownership(param);
        if matches!(ownership.mode, corvid_abi::AbiOwnershipMode::Borrowed) {
            if let Some(lifetime) = ownership.lifetime.as_deref() {
                if lifetime != "call" && !lifetimes.iter().any(|existing| existing == lifetime) {
                    lifetimes.push(lifetime.to_string());
                }
            }
        }
    }
    if lifetimes.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            lifetimes
                .iter()
                .map(|lifetime| format!("'{lifetime}"))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn render_dangerous_agent_body(agent: &corvid_abi::AbiAgent) -> Result<String> {
    let mut out = String::new();
    out.push_str("        let args_json = json!([\n");
    for param in &agent.params {
        out.push_str(&format!("            {},\n", snake_case(&param.name)));
    }
    out.push_str("        ]);\n");
    out.push_str("        let args_json = serde_json::to_string(&args_json)\n");
    out.push_str("            .map_err(|err| CorvidError::Decode(err.to_string()))?;\n");
    out.push_str(&format!(
        "        match self.call_json_agent_once::<{}>({}, &args_json)? {{\n",
        rust_public_type(&agent.return_type),
        rust_string_literal(&agent.name)
    ));
    out.push_str("            CallAttempt::Completed(value) => Ok(value),\n");
    out.push_str("            CallAttempt::ApprovalRequired(request) => match approver.decide(&request) {\n");
    out.push_str("                ApprovalDecision::Reject => Err(CorvidError::ApprovalDenied(request)),\n");
    out.push_str("                ApprovalDecision::Accept => {\n");
    out.push_str("                    self.mark_preapproved_request(&request.site_name, &request.args_json)?;\n");
    out.push_str(&render_direct_invoke_body(agent, "                    ")?);
    out.push_str("                }\n");
    out.push_str("            },\n");
    out.push_str("        }\n");
    Ok(out)
}

fn render_direct_agent_body(agent: &corvid_abi::AbiAgent) -> Result<String> {
    render_direct_invoke_body(agent, "        ")
}

fn render_direct_invoke_body(agent: &corvid_abi::AbiAgent, indent: &str) -> Result<String> {
    let mut out = String::new();
    let return_ownership = effective_return_ownership(agent);
    let return_destructor = return_ownership
        .destructor
        .as_ref()
        .map(|destructor| destructor.symbol.as_str())
        .unwrap_or("corvid_free_string");
    let mut argtypes = Vec::new();
    let mut call_args = Vec::new();
    let mut prelude = String::new();
    for (index, param) in agent.params.iter().enumerate() {
        let ident = snake_case(&param.name);
        let ffi_type = rust_c_abi_param_type(&param.ty)?;
        argtypes.push(ffi_type.to_string());
        if matches!(
            crate::ffi_scalar_kind(&param.ty),
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId)
        ) {
            writeln!(
                &mut prelude,
                "{indent}let arg_{index} = CString::new({ident}).map_err(|err| CorvidError::BadArgs(err.to_string()))?;"
            )
            .unwrap();
            call_args.push(format!("arg_{index}.as_ptr()"));
        } else {
            call_args.push(ident);
        }
    }
    if returns_grounded(&agent.return_type) {
        argtypes.push("*mut u64".to_string());
    }
    argtypes.push("*mut u64".to_string());
    let return_ty = if returns_grounded(&agent.return_type) {
        rust_c_abi_return_type(grounded_inner(agent.return_type()).unwrap())?
    } else {
        rust_c_abi_return_type(&agent.return_type)?
    };
    let fn_sig = format!(
        "unsafe extern \"C\" fn({}) -> {}",
        argtypes.join(", "),
        return_ty
    );
    out.push_str(&prelude);
    out.push_str(&format!("{indent}unsafe {{\n"));
    let symbol_bytes = format!("b\"{}\"", agent.symbol);
    out.push_str(&format!(
        "{indent}    let symbol: Symbol<{fn_sig}> = self.library.get({symbol}).map_err(|err| CorvidError::Load(err.to_string()))?;\n",
        symbol = symbol_bytes
    ));
    if returns_grounded(&agent.return_type) {
        out.push_str(&format!("{indent}    let mut grounded_handle = 0u64;\n"));
    }
    out.push_str(&format!("{indent}    let mut observation_handle = 0u64;\n"));
    let mut all_args = call_args;
    if returns_grounded(&agent.return_type) {
        all_args.push("&mut grounded_handle".to_string());
    }
    all_args.push("&mut observation_handle".to_string());
    out.push_str(&format!(
        "{indent}    let value = symbol({});\n",
        all_args.join(", ")
    ));
    if returns_grounded(&agent.return_type) {
        match grounded_inner_kind(&agent.return_type).unwrap() {
            corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId => {
                out.push_str(&format!(
                    "{indent}    let payload = take_owned_c_string(&self.library, value, \"corvid_free_string\")?;\n",
                ));
            }
            _ => out.push_str(&format!("{indent}    let payload = value;\n")),
        }
        out.push_str(&format!(
            "{indent}    let grounded = Grounded::new(payload, self.library.clone(), grounded_handle, {:?});\n",
            return_destructor
        ));
        out.push_str(&format!(
            "{indent}    Ok((grounded, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
        ));
    } else {
        match crate::ffi_scalar_kind(&agent.return_type) {
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId) => {
                out.push_str(&format!(
                    "{indent}    let payload = take_owned_c_string(&self.library, value, {:?})?;\n",
                    return_destructor
                ));
                out.push_str(&format!(
                    "{indent}    Ok((payload, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
            Some(corvid_abi::ScalarTypeName::Nothing) => {
                out.push_str(&format!(
                    "{indent}    Ok(((), Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
            _ => {
                out.push_str(&format!(
                    "{indent}    Ok((value, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
        }
    }
    out.push_str(&format!("{indent}}}\n"));
    Ok(out)
}
