use std::fmt::Write as _;
use std::path::PathBuf;

use anyhow::Result;

use crate::{
    effective_param_ownership, effective_return_ownership, grounded_inner_kind,
    is_generated_user_agent, pascal_case, returns_grounded, rust_c_abi_param_type,
    rust_c_abi_return_type, rust_f64_literal, rust_public_param_type, rust_public_type,
    rust_string_literal, snake_case, BindingContext, GeneratedFile,
};

pub(crate) fn render(context: &BindingContext) -> Result<Vec<GeneratedFile>> {
    let mut files = Vec::new();
    files.push(GeneratedFile {
        relative_path: PathBuf::from("Cargo.toml"),
        contents: render_cargo_toml(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("README.md"),
        contents: render_readme(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("src/lib.rs"),
        contents: render_lib_rs(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("src/common.rs"),
        contents: render_common_rs(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("src/types.rs"),
        contents: render_types_rs(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("src/catalog.rs"),
        contents: render_catalog_rs(),
    });
    for agent in context
        .abi
        .agents
        .iter()
        .filter(|agent| is_generated_user_agent(agent))
    {
        let module_name = snake_case(&agent.name);
        files.push(GeneratedFile {
            relative_path: PathBuf::from(format!("src/{module_name}.rs")),
            contents: render_agent_module(context, agent)?,
        });
    }
    Ok(files)
}


mod cargo;
mod common_template;
mod lib_template;
use cargo::{render_cargo_toml, render_readme};
use common_template::render_common_rs;
use lib_template::render_lib_rs;


fn render_types_rs(context: &BindingContext) -> String {
    let mut out = String::new();
    out.push_str("// @generated by corvid bind rust.\n");
    out.push_str(&format!(
        "// descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("// corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "// descriptor generated_at: {}\n\n",
        context.abi.generated_at
    ));
    out.push_str("use serde::{Deserialize, Serialize};\n\n");
    for ty in &context.abi.types {
        if ty.kind != "struct" {
            continue;
        }
        out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", pascal_case(&ty.name)));
        for field in &ty.fields {
            out.push_str(&format!(
                "    pub {}: {},\n",
                snake_case(&field.name),
                rust_public_type(&field.r#type)
            ));
        }
        out.push_str("}\n\n");
    }
    out
}

fn render_catalog_rs() -> String {
    r#"// @generated by corvid bind rust.
use std::ffi::c_char;

use libloading::Symbol;
use serde_json::json;

use crate::common::{
    read_c_string_lossy, Client, CorvidAgentHandleRaw, CorvidError, CorvidFindAgentsResultRaw,
    CorvidResult, TrustTier, CORVID_FIND_AGENTS_OK,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FindAgentsStatus {
    Ok,
    BadJson,
    UnknownDimension,
    OpMismatch,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reversibility {
    Reversible,
    Irreversible,
}

#[derive(Debug, Clone)]
pub struct AgentInfo {
    pub name: String,
    pub symbol: String,
    pub source_file: String,
    pub source_line: u32,
    pub trust_tier: TrustTier,
    pub cost_bound_usd: Option<f64>,
    pub reversible: Option<Reversibility>,
    pub replayable: bool,
    pub deterministic: bool,
    pub dangerous: bool,
    pub pub_extern_c: bool,
    pub requires_approval: bool,
    pub grounded_source_count: u32,
    pub param_count: u32,
}

pub struct Catalog<'a> {
    client: &'a Client,
}

pub struct CatalogQuery<'a> {
    client: &'a Client,
    clauses: Vec<serde_json::Value>,
}

impl<'a> Catalog<'a> {
    pub(crate) fn new(client: &'a Client) -> Self {
        Self { client }
    }

    pub fn query(&self) -> CatalogQuery<'a> {
        CatalogQuery {
            client: self.client,
            clauses: Vec::new(),
        }
    }

    pub fn where_trust_tier_le(&self, tier: TrustTier) -> CatalogQuery<'a> {
        self.query().where_trust_tier_le(tier)
    }

    pub fn where_cost_bound_usd_le(&self, usd: f64) -> CatalogQuery<'a> {
        self.query().where_cost_bound_usd_le(usd)
    }

    pub fn not_dangerous(&self) -> CatalogQuery<'a> {
        self.query().not_dangerous()
    }
}

impl<'a> CatalogQuery<'a> {
    fn push_clause(mut self, clause: serde_json::Value) -> Self {
        self.clauses.push(clause);
        self
    }

    pub fn where_trust_tier_le(self, tier: TrustTier) -> Self {
        let value = match tier {
            TrustTier::Autonomous => "autonomous",
            TrustTier::HumanRequired => "human_required",
            TrustTier::SecurityReview => "security_review",
        };
        self.push_clause(json!({"dim":"trust_tier","op":"le","value":value}))
    }

    pub fn where_cost_bound_usd_le(self, usd: f64) -> Self {
        self.push_clause(json!({"dim":"cost_bound_usd","op":"le","value":usd}))
    }

    pub fn where_latency_p99_ms_le(self, ms: f64) -> Self {
        self.push_clause(json!({"dim":"latency_p99_ms","op":"le","value":ms}))
    }

    pub fn not_dangerous(self) -> Self {
        self.push_clause(json!({"dim":"dangerous","op":"eq","value":false}))
    }

    pub fn replayable(self) -> Self {
        self.push_clause(json!({"dim":"replayable","op":"eq","value":true}))
    }

    pub fn deterministic(self) -> Self {
        self.push_clause(json!({"dim":"deterministic","op":"eq","value":true}))
    }

    pub fn find(self) -> CorvidResult<Vec<AgentInfo>> {
        let filter = if self.clauses.len() == 1 {
            self.clauses.into_iter().next().unwrap()
        } else {
            json!({ "all": self.clauses })
        };
        let filter_json = serde_json::to_string(&filter)
            .map_err(|err| CorvidError::Decode(err.to_string()))?;
        unsafe {
            let find: Symbol<
                unsafe extern "C" fn(*const c_char, usize, *mut usize, usize) -> CorvidFindAgentsResultRaw,
            > = self
                .client
                .library
                .get(b"corvid_find_agents_where")
                .map_err(|err| CorvidError::Load(err.to_string()))?;
            let list: Symbol<unsafe extern "C" fn(*mut CorvidAgentHandleRaw, usize) -> usize> = self
                .client
                .library
                .get(b"corvid_list_agents")
                .map_err(|err| CorvidError::Load(err.to_string()))?;

            let filter_json = std::ffi::CString::new(filter_json)
                .map_err(|err| CorvidError::BadArgs(err.to_string()))?;
            let raw = find(filter_json.as_ptr(), filter_json.as_bytes().len(), std::ptr::null_mut(), 0);
        if raw.status != CORVID_FIND_AGENTS_OK {
                return Err(CorvidError::Runtime(read_c_string_lossy(raw.error_message)));
            }
            let mut matched = vec![0usize; raw.matched_count];
            let raw = find(
                filter_json.as_ptr(),
                filter_json.as_bytes().len(),
                matched.as_mut_ptr(),
                matched.len(),
            );
            if raw.status != CORVID_FIND_AGENTS_OK {
                return Err(CorvidError::Runtime(read_c_string_lossy(raw.error_message)));
            }
            let total = list(std::ptr::null_mut(), 0);
            let mut handles = vec![
                CorvidAgentHandleRaw {
                    name: std::ptr::null(),
                    symbol: std::ptr::null(),
                    source_file: std::ptr::null(),
                    source_line: 0,
                    trust_tier: 0,
                    cost_bound_usd: 0.0,
                    reversible: 0,
                    latency_instant: 0,
                    replayable: 0,
                    deterministic: 0,
                    dangerous: 0,
                    pub_extern_c: 0,
                    requires_approval: 0,
                    grounded_source_count: 0,
                    param_count: 0,
                };
                total
            ];
            list(handles.as_mut_ptr(), handles.len());
            Ok(matched
                .into_iter()
                .filter_map(|index| handles.get(index).copied())
                .map(AgentInfo::from_raw)
                .collect())
        }
    }
}

impl AgentInfo {
    fn from_raw(raw: CorvidAgentHandleRaw) -> Self {
        Self {
            name: read_c_string_lossy(raw.name),
            symbol: read_c_string_lossy(raw.symbol),
            source_file: read_c_string_lossy(raw.source_file),
            source_line: raw.source_line,
            trust_tier: match raw.trust_tier {
                1 => TrustTier::HumanRequired,
                2 => TrustTier::SecurityReview,
                _ => TrustTier::Autonomous,
            },
            cost_bound_usd: if raw.cost_bound_usd.is_finite() {
                Some(raw.cost_bound_usd)
            } else {
                None
            },
            reversible: match raw.reversible {
                0 => Some(Reversibility::Reversible),
                1 => Some(Reversibility::Irreversible),
                _ => None,
            },
            replayable: raw.replayable != 0,
            deterministic: raw.deterministic != 0,
            dangerous: raw.dangerous != 0,
            pub_extern_c: raw.pub_extern_c != 0,
            requires_approval: raw.requires_approval != 0,
            grounded_source_count: raw.grounded_source_count,
            param_count: raw.param_count,
        }
    }
}
"#
    .to_string()
}

fn render_agent_module(context: &BindingContext, agent: &corvid_abi::AbiAgent) -> Result<String> {
    let marker = pascal_case(&agent.name);
    let api_trait = format!("{marker}Api");
    let method_name = snake_case(&agent.name);
    let return_type = if returns_grounded(&agent.return_type) {
        format!(
            "Grounded<{}>",
            rust_public_type(
                grounded_inner(agent.return_type()).unwrap_or(&agent.return_type)
            )
        )
    } else {
        rust_public_type(&agent.return_type)
    };

    let mut out = String::new();
    out.push_str("// @generated by corvid bind rust.\n");
    out.push_str(&format!(
        "// descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("// corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "// descriptor generated_at: {}\n",
        context.abi.generated_at
    ));
    out.push_str("use std::ffi::CString;\n\n");
    out.push_str("use libloading::Symbol;\n");
    out.push_str("use serde_json::json;\n\n");
    out.push_str("use crate::common::{\n");
    out.push_str("    take_owned_c_string, ApprovalDecision, Approver, CallAttempt, CallStatus, Client,\n");
    out.push_str("    CorvidError, CorvidResult, Grounded, Observation, TrustTier,\n");
    out.push_str("};\n");
    out.push_str("use crate::types::*;\n\n");
    out.push_str(&format!("pub struct {marker};\n\n"));
    out.push_str(&format!("impl {marker} {{\n"));
    out.push_str(&format!(
        "    pub const NAME: &str = {};\n",
        rust_string_literal(&agent.name)
    ));
    out.push_str(&format!(
        "    pub const SYMBOL: &str = {};\n",
        rust_string_literal(&agent.symbol)
    ));
    out.push_str(&format!(
        "    pub const TRUST_TIER: TrustTier = TrustTier::{};\n",
        match agent.abi_effect_trust_tier().as_deref() {
            Some("human_required") => "HumanRequired",
            Some("security_review") => "SecurityReview",
            _ => "Autonomous",
        }
    ));
    if let Some(budget) = &agent.budget {
        out.push_str(&format!(
            "    pub const COST_BOUND_USD: Option<f64> = Some({});\n",
            rust_f64_literal(budget.usd_per_call)
        ));
    } else {
        out.push_str("    pub const COST_BOUND_USD: Option<f64> = None;\n");
    }
    out.push_str(&format!(
        "    pub const IS_DANGEROUS: bool = {};\n",
        if agent.attributes.dangerous { "true" } else { "false" }
    ));
    out.push_str(&format!(
        "    pub const RETURNS_GROUNDED: bool = {};\n",
        if returns_grounded(&agent.return_type) { "true" } else { "false" }
    ));
    out.push_str("}\n\n");

    let generics = render_method_generics(agent);
    out.push_str(&format!("pub trait {api_trait} {{\n"));
    out.push_str(&format!(
        "    fn {method_name}{generics}(&self{sig}) -> CorvidResult<({return_type}, Observation)>;\n",
        generics = generics,
        sig = render_trait_signature_params(agent)
    ));
    out.push_str("}\n\n");
    out.push_str(&format!("impl {api_trait} for Client {{\n"));
    out.push_str(&format!(
        "    fn {method_name}{generics}(&self{sig}) -> CorvidResult<({return_type}, Observation)> {{\n",
        generics = generics,
        sig = render_trait_signature_params(agent)
    ));
    if agent.attributes.dangerous {
        out.push_str(&render_dangerous_agent_body(agent)?);
    } else {
        out.push_str(&render_direct_agent_body(agent)?);
    }
    out.push_str("    }\n");
    out.push_str("}\n");

    Ok(out)
}

trait AbiAgentExt {
    fn abi_effect_trust_tier(&self) -> Option<String>;
    fn return_type(&self) -> &corvid_abi::TypeDescription;
}

impl AbiAgentExt for corvid_abi::AbiAgent {
    fn abi_effect_trust_tier(&self) -> Option<String> {
        self.effects.trust_tier.clone()
    }

    fn return_type(&self) -> &corvid_abi::TypeDescription {
        &self.return_type
    }
}

fn grounded_inner(ty: &corvid_abi::TypeDescription) -> Option<&corvid_abi::TypeDescription> {
    match ty {
        corvid_abi::TypeDescription::Grounded { grounded } => Some(grounded.inner.as_ref()),
        _ => None,
    }
}

fn render_trait_signature_params(agent: &corvid_abi::AbiAgent) -> String {
    let mut out = String::new();
    for param in &agent.params {
        out.push_str(", ");
        out.push_str(&snake_case(&param.name));
        out.push_str(": ");
        out.push_str(&rust_public_param_type(param));
    }
    if agent.attributes.dangerous {
        out.push_str(", approver: &dyn Approver");
    }
    out
}

fn render_method_generics(agent: &corvid_abi::AbiAgent) -> String {
    let mut lifetimes = Vec::new();
    for param in &agent.params {
        let ownership = effective_param_ownership(param);
        if matches!(ownership.mode, corvid_abi::AbiOwnershipMode::Borrowed) {
            if let Some(lifetime) = ownership.lifetime.as_deref() {
                if lifetime != "call" && !lifetimes.iter().any(|existing| existing == lifetime) {
                    lifetimes.push(lifetime.to_string());
                }
            }
        }
    }
    if lifetimes.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            lifetimes
                .iter()
                .map(|lifetime| format!("'{lifetime}"))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn render_dangerous_agent_body(agent: &corvid_abi::AbiAgent) -> Result<String> {
    let mut out = String::new();
    out.push_str("        let args_json = json!([\n");
    for param in &agent.params {
        out.push_str(&format!("            {},\n", snake_case(&param.name)));
    }
    out.push_str("        ]);\n");
    out.push_str("        let args_json = serde_json::to_string(&args_json)\n");
    out.push_str("            .map_err(|err| CorvidError::Decode(err.to_string()))?;\n");
    out.push_str(&format!(
        "        match self.call_json_agent_once::<{}>({}, &args_json)? {{\n",
        rust_public_type(&agent.return_type),
        rust_string_literal(&agent.name)
    ));
    out.push_str("            CallAttempt::Completed(value) => Ok(value),\n");
    out.push_str("            CallAttempt::ApprovalRequired(request) => match approver.decide(&request) {\n");
    out.push_str("                ApprovalDecision::Reject => Err(CorvidError::ApprovalDenied(request)),\n");
    out.push_str("                ApprovalDecision::Accept => {\n");
    out.push_str("                    self.mark_preapproved_request(&request.site_name, &request.args_json)?;\n");
    out.push_str(&render_direct_invoke_body(agent, "                    ")?);
    out.push_str("                }\n");
    out.push_str("            },\n");
    out.push_str("        }\n");
    Ok(out)
}

fn render_direct_agent_body(agent: &corvid_abi::AbiAgent) -> Result<String> {
    render_direct_invoke_body(agent, "        ")
}

fn render_direct_invoke_body(agent: &corvid_abi::AbiAgent, indent: &str) -> Result<String> {
    let mut out = String::new();
    let return_ownership = effective_return_ownership(agent);
    let return_destructor = return_ownership
        .destructor
        .as_ref()
        .map(|destructor| destructor.symbol.as_str())
        .unwrap_or("corvid_free_string");
    let mut argtypes = Vec::new();
    let mut call_args = Vec::new();
    let mut prelude = String::new();
    for (index, param) in agent.params.iter().enumerate() {
        let ident = snake_case(&param.name);
        let ffi_type = rust_c_abi_param_type(&param.ty)?;
        argtypes.push(ffi_type.to_string());
        if matches!(
            crate::ffi_scalar_kind(&param.ty),
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId)
        ) {
            writeln!(
                &mut prelude,
                "{indent}let arg_{index} = CString::new({ident}).map_err(|err| CorvidError::BadArgs(err.to_string()))?;"
            )
            .unwrap();
            call_args.push(format!("arg_{index}.as_ptr()"));
        } else {
            call_args.push(ident);
        }
    }
    if returns_grounded(&agent.return_type) {
        argtypes.push("*mut u64".to_string());
    }
    argtypes.push("*mut u64".to_string());
    let return_ty = if returns_grounded(&agent.return_type) {
        rust_c_abi_return_type(grounded_inner(agent.return_type()).unwrap())?
    } else {
        rust_c_abi_return_type(&agent.return_type)?
    };
    let fn_sig = format!(
        "unsafe extern \"C\" fn({}) -> {}",
        argtypes.join(", "),
        return_ty
    );
    out.push_str(&prelude);
    out.push_str(&format!("{indent}unsafe {{\n"));
    let symbol_bytes = format!("b\"{}\"", agent.symbol);
    out.push_str(&format!(
        "{indent}    let symbol: Symbol<{fn_sig}> = self.library.get({symbol}).map_err(|err| CorvidError::Load(err.to_string()))?;\n",
        symbol = symbol_bytes
    ));
    if returns_grounded(&agent.return_type) {
        out.push_str(&format!("{indent}    let mut grounded_handle = 0u64;\n"));
    }
    out.push_str(&format!("{indent}    let mut observation_handle = 0u64;\n"));
    let mut all_args = call_args;
    if returns_grounded(&agent.return_type) {
        all_args.push("&mut grounded_handle".to_string());
    }
    all_args.push("&mut observation_handle".to_string());
    out.push_str(&format!(
        "{indent}    let value = symbol({});\n",
        all_args.join(", ")
    ));
    if returns_grounded(&agent.return_type) {
        match grounded_inner_kind(&agent.return_type).unwrap() {
            corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId => {
                out.push_str(&format!(
                    "{indent}    let payload = take_owned_c_string(&self.library, value, \"corvid_free_string\")?;\n",
                ));
            }
            _ => out.push_str(&format!("{indent}    let payload = value;\n")),
        }
        out.push_str(&format!(
            "{indent}    let grounded = Grounded::new(payload, self.library.clone(), grounded_handle, {:?});\n",
            return_destructor
        ));
        out.push_str(&format!(
            "{indent}    Ok((grounded, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
        ));
    } else {
        match crate::ffi_scalar_kind(&agent.return_type) {
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId) => {
                out.push_str(&format!(
                    "{indent}    let payload = take_owned_c_string(&self.library, value, {:?})?;\n",
                    return_destructor
                ));
                out.push_str(&format!(
                    "{indent}    Ok((payload, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
            Some(corvid_abi::ScalarTypeName::Nothing) => {
                out.push_str(&format!(
                    "{indent}    Ok(((), Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
            _ => {
                out.push_str(&format!(
                    "{indent}    Ok((value, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
        }
    }
    out.push_str(&format!("{indent}}}\n"));
    Ok(out)
}
