use std::fmt::Write as _;
use std::path::PathBuf;

use anyhow::Result;

use crate::{
    effective_param_ownership, effective_return_ownership, grounded_inner_kind,
    is_generated_user_agent, pascal_case, returns_grounded, rust_c_abi_param_type,
    rust_c_abi_return_type, rust_f64_literal, rust_public_param_type, rust_public_type,
    rust_string_literal, snake_case, BindingContext, GeneratedFile,
};

pub(crate) fn render(context: &BindingContext) -> Result<Vec<GeneratedFile>> {
    let mut files = Vec::new();
    files.push(GeneratedFile {
        relative_path: PathBuf::from("Cargo.toml"),
        contents: render_cargo_toml(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("README.md"),
        contents: render_readme(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("src/lib.rs"),
        contents: render_lib_rs(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("src/common.rs"),
        contents: render_common_rs(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("src/types.rs"),
        contents: render_types_rs(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("src/catalog.rs"),
        contents: render_catalog_rs(),
    });
    for agent in context
        .abi
        .agents
        .iter()
        .filter(|agent| is_generated_user_agent(agent))
    {
        let module_name = snake_case(&agent.name);
        files.push(GeneratedFile {
            relative_path: PathBuf::from(format!("src/{module_name}.rs")),
            contents: render_agent_module(context, agent)?,
        });
    }
    Ok(files)
}


mod cargo;
use cargo::{render_cargo_toml, render_readme};


fn render_lib_rs(context: &BindingContext) -> String {
    let mut out = String::new();
    out.push_str("// @generated by corvid bind rust.\n");
    out.push_str(&format!(
        "// descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("// corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "// descriptor generated_at: {}\n",
        context.abi.generated_at
    ));
    out.push_str("pub mod common;\n");
    out.push_str("pub mod catalog;\n");
    out.push_str("pub mod types;\n");
    for agent in context
        .abi
        .agents
        .iter()
        .filter(|agent| is_generated_user_agent(agent))
    {
        out.push_str(&format!("pub mod {};\n", snake_case(&agent.name)));
    }
    out.push_str("\n");
    out.push_str(
        "pub use catalog::{AgentInfo, Catalog, CatalogQuery, FindAgentsStatus, Reversibility};\n",
    );
    out.push_str("pub use common::{\n");
    out.push_str("    ApprovalDecision, ApprovalRequest, Approver, CallStatus, Client, CorvidError,\n");
    out.push_str("    CorvidResult, DescriptorDrift, Grounded, GroundedProvenance, Observation,\n");
    out.push_str("    TrustTier, Weak, DESCRIPTOR_HASH_HEX,\n");
    out.push_str("};\n");
    out.push_str("pub use types::*;\n");
    for agent in context
        .abi
        .agents
        .iter()
        .filter(|agent| is_generated_user_agent(agent))
    {
        let module_name = snake_case(&agent.name);
        let api_trait = format!("{}Api", pascal_case(&agent.name));
        out.push_str(&format!(
            "pub use {module_name}::{{{api_trait}, {marker}}};\n",
            marker = pascal_case(&agent.name)
        ));
    }
    out
}

fn render_common_rs(context: &BindingContext) -> String {
    format!(
        r#"// @generated by corvid bind rust.
// descriptor sha256: {hash}
// corvid-bind version: {version}
// descriptor generated_at: {generated_at}

use std::ffi::{{c_char, CStr, CString}};
use std::fmt;
use std::path::Path;
use std::sync::Arc;

use libloading::{{Library, Symbol}};
use serde::de::DeserializeOwned;
use serde::{{Deserialize, Serialize}};

pub const DESCRIPTOR_HASH_HEX: &str = "{hash}";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TrustTier {{
    Autonomous,
    HumanRequired,
    SecurityReview,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CallStatus {{
    Ok,
    AgentNotFound,
    BadArgs,
    UnsupportedSig,
    ApprovalRequired,
    BudgetExceeded,
    RuntimeError,
}}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DescriptorDrift {{
    pub expected: String,
    pub actual: String,
}}

impl fmt::Display for DescriptorDrift {{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{
        write!(
            f,
            "binding generated from descriptor sha256:{{}} but cdylib ships descriptor sha256:{{}}",
            self.expected, self.actual
        )
    }}
}}

impl std::error::Error for DescriptorDrift {{}}

#[derive(Debug)]
pub enum CorvidError {{
    Load(String),
    DescriptorDrift(DescriptorDrift),
    ApprovalRequired(ApprovalRequest),
    ApprovalDenied(ApprovalRequest),
    BadArgs(String),
    UnsupportedSignature(String),
    BudgetExceeded(String),
    Runtime(String),
    Decode(String),
}}

impl fmt::Display for CorvidError {{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{
        match self {{
            Self::Load(message) => write!(f, "load error: {{message}}"),
            Self::DescriptorDrift(err) => err.fmt(f),
            Self::ApprovalRequired(request) => write!(f, "approval required for `{{}}`", request.site_name),
            Self::ApprovalDenied(request) => write!(f, "approval denied for `{{}}`", request.site_name),
            Self::BadArgs(message) => write!(f, "bad args: {{message}}"),
            Self::UnsupportedSignature(message) => write!(f, "unsupported signature: {{message}}"),
            Self::BudgetExceeded(message) => write!(f, "budget exceeded: {{message}}"),
            Self::Runtime(message) => write!(f, "runtime error: {{message}}"),
            Self::Decode(message) => write!(f, "decode error: {{message}}"),
        }}
    }}
}}

impl std::error::Error for CorvidError {{}}

pub type CorvidResult<T> = Result<T, CorvidError>;

pub(crate) const CORVID_APPROVAL_REJECT: i32 = 1;
pub(crate) const CORVID_CALL_OK: i32 = 0;
pub(crate) const CORVID_CALL_AGENT_NOT_FOUND: i32 = 1;
pub(crate) const CORVID_CALL_BAD_ARGS: i32 = 2;
pub(crate) const CORVID_CALL_UNSUPPORTED_SIG: i32 = 3;
pub(crate) const CORVID_CALL_APPROVAL_REQUIRED: i32 = 4;
pub(crate) const CORVID_CALL_BUDGET_EXCEEDED: i32 = 5;
pub(crate) const CORVID_CALL_RUNTIME_ERROR: i32 = 6;
pub(crate) const CORVID_FIND_AGENTS_OK: i32 = 0;

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct CorvidApprovalRequiredRaw {{
    pub site_name: *const c_char,
    pub predicate_json: *const c_char,
    pub args_json: *const c_char,
    pub rationale_prompt: *const c_char,
}}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct CorvidFindAgentsResultRaw {{
    pub status: i32,
    pub matched_count: usize,
    pub error_message: *const c_char,
}}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct CorvidAgentHandleRaw {{
    pub name: *const c_char,
    pub symbol: *const c_char,
    pub source_file: *const c_char,
    pub source_line: u32,
    pub trust_tier: u8,
    pub cost_bound_usd: f64,
    pub reversible: u8,
    pub latency_instant: u8,
    pub replayable: u8,
    pub deterministic: u8,
    pub dangerous: u8,
    pub pub_extern_c: u8,
    pub requires_approval: u8,
    pub grounded_source_count: u32,
    pub param_count: u32,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ApprovalRequest {{
    pub site_name: String,
    pub predicate_json: String,
    pub args_json: String,
    pub rationale_prompt: String,
}}

impl ApprovalRequest {{
    pub(crate) unsafe fn from_raw(raw: &CorvidApprovalRequiredRaw) -> Self {{
        Self {{
            site_name: read_c_string_lossy(raw.site_name),
            predicate_json: read_c_string_lossy(raw.predicate_json),
            args_json: read_c_string_lossy(raw.args_json),
            rationale_prompt: read_c_string_lossy(raw.rationale_prompt),
        }}
    }}
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApprovalDecision {{
    Accept,
    Reject,
}}

pub trait Approver {{
    fn decide(&self, request: &ApprovalRequest) -> ApprovalDecision;
}}

#[derive(Debug, Clone)]
pub struct Client {{
    pub(crate) library: Arc<Library>,
}}

impl Client {{
    pub fn load(path: impl AsRef<Path>) -> CorvidResult<Self> {{
        let library = unsafe {{ Library::new(path.as_ref()) }}
            .map_err(|err| CorvidError::Load(err.to_string()))?;
        let client = Self {{
            library: Arc::new(library),
        }};
        client.verify_descriptor_hash()?;
        Ok(client)
    }}

    pub fn catalog(&self) -> crate::catalog::Catalog<'_> {{
        crate::catalog::Catalog::new(self)
    }}

    pub(crate) fn verify_descriptor_hash(&self) -> CorvidResult<()> {{
        let actual = self.descriptor_hash_hex()?;
        if actual != DESCRIPTOR_HASH_HEX {{
            return Err(CorvidError::DescriptorDrift(DescriptorDrift {{
                expected: DESCRIPTOR_HASH_HEX.to_string(),
                actual,
            }}));
        }}
        Ok(())
    }}

    pub(crate) fn descriptor_hash_hex(&self) -> CorvidResult<String> {{
        unsafe {{
            let symbol: Symbol<unsafe extern "C" fn(*mut u8)> = self
                .library
                .get(b"corvid_abi_descriptor_hash")
                .map_err(|err| CorvidError::Load(err.to_string()))?;
            let mut bytes = [0u8; 32];
            symbol(bytes.as_mut_ptr());
            Ok(hex_bytes(&bytes))
        }}
    }}

    pub(crate) fn call_json_agent_once<Ret: DeserializeOwned>(
        &self,
        agent_name: &str,
        args_json: &str,
    ) -> CorvidResult<CallAttempt<Ret>> {{
        unsafe {{
            let call: unsafe extern "C" fn(
                *const c_char,
                *const c_char,
                usize,
                *mut *mut c_char,
                *mut usize,
                *mut u64,
                *mut CorvidApprovalRequiredRaw,
            ) -> i32 = *self
                .library
                .get(b"corvid_call_agent")
                .map_err(|err| CorvidError::Load(err.to_string()))?;
            let free_result: unsafe extern "C" fn(*mut c_char) = *self
                .library
                .get(b"corvid_free_result")
                .map_err(|err| CorvidError::Load(err.to_string()))?;

            let agent_name_c = CString::new(agent_name)
                .map_err(|err| CorvidError::BadArgs(err.to_string()))?;
            let args_json = CString::new(args_json)
                .map_err(|err| CorvidError::BadArgs(err.to_string()))?;
            let mut result_ptr = std::ptr::null_mut();
            let mut result_len = 0usize;
            let mut observation_handle = 0u64;
            let mut approval = CorvidApprovalRequiredRaw {{
                site_name: std::ptr::null(),
                predicate_json: std::ptr::null(),
                args_json: std::ptr::null(),
                rationale_prompt: std::ptr::null(),
            }};
            let status = call(
                agent_name_c.as_ptr(),
                args_json.as_ptr(),
                args_json.as_bytes().len(),
                &mut result_ptr,
                &mut result_len,
                &mut observation_handle,
                &mut approval,
            );

            let result_json = if result_ptr.is_null() {{
                None
            }} else {{
                let slice = std::slice::from_raw_parts(result_ptr as *const u8, result_len);
                let text = String::from_utf8(slice.to_vec())
                    .map_err(|err| CorvidError::Decode(err.to_string()))?;
                free_result(result_ptr);
                Some(text)
            }};

            match status {{
                CORVID_CALL_OK => {{
                    let observation = Observation::new(
                        self.library.clone(),
                        observation_handle,
                        "corvid_observation_release",
                    );
                    let payload = serde_json::from_str::<Ret>(
                        result_json.as_deref().unwrap_or("null"),
                    )
                    .map_err(|err| CorvidError::Decode(err.to_string()))?;
                    Ok(CallAttempt::Completed((payload, observation)))
                }}
                CORVID_CALL_APPROVAL_REQUIRED => {{
                    self.release_observation_handle(observation_handle);
                    let request = ApprovalRequest::from_raw(&approval);
                    Ok(CallAttempt::ApprovalRequired(request))
                }}
                CORVID_CALL_AGENT_NOT_FOUND => {{
                    self.release_observation_handle(observation_handle);
                    Err(CorvidError::Runtime(format!(
                        "agent `{{agent_name}}` not found"
                    )))
                }}
                CORVID_CALL_BAD_ARGS => {{
                    self.release_observation_handle(observation_handle);
                    Err(CorvidError::BadArgs(
                        result_json.unwrap_or_else(|| "runtime rejected arguments".to_string()),
                    ))
                }}
                CORVID_CALL_UNSUPPORTED_SIG => {{
                    self.release_observation_handle(observation_handle);
                    Err(CorvidError::UnsupportedSignature(
                        result_json.unwrap_or_else(|| "runtime rejected unsupported signature".to_string()),
                    ))
                }}
                CORVID_CALL_BUDGET_EXCEEDED => {{
                    self.release_observation_handle(observation_handle);
                    Err(CorvidError::BudgetExceeded(
                        result_json.unwrap_or_else(|| "runtime budget exceeded".to_string()),
                    ))
                }}
                CORVID_CALL_RUNTIME_ERROR => {{
                    self.release_observation_handle(observation_handle);
                    Err(CorvidError::Runtime(
                        result_json.unwrap_or_else(|| "runtime error".to_string()),
                    ))
                }}
                other => {{
                    self.release_observation_handle(observation_handle);
                    Err(CorvidError::Runtime(format!(
                        "runtime returned unknown call status {{other}}"
                    )))
                }}
            }}
        }}
    }}

    pub(crate) fn mark_preapproved_request(&self, site_name: &str, args_json: &str) -> CorvidResult<()> {{
        unsafe {{
            let mark: unsafe extern "C" fn(*const c_char, *const c_char, usize) -> bool = *self
                .library
                .get(b"corvid_mark_preapproved_request")
                .map_err(|err| CorvidError::Load(err.to_string()))?;
            let site_name = CString::new(site_name)
                .map_err(|err| CorvidError::BadArgs(err.to_string()))?;
            let args_json = CString::new(args_json)
                .map_err(|err| CorvidError::BadArgs(err.to_string()))?;
            if mark(site_name.as_ptr(), args_json.as_ptr(), args_json.as_bytes().len()) {{
                Ok(())
            }} else {{
                Err(CorvidError::Runtime(
                    "runtime rejected preapproved approval request".to_string(),
                ))
            }}
        }}
    }}

    fn release_observation_handle(&self, handle: u64) {{
        if handle == 0 {{
            return;
        }}
        unsafe {{
            if let Ok(symbol) =
                self.library.get::<unsafe extern "C" fn(u64)>(b"corvid_observation_release")
            {{
                symbol(handle);
            }}
        }}
    }}
}}

pub(crate) enum CallAttempt<T> {{
    Completed((T, Observation)),
    ApprovalRequired(ApprovalRequest),
}}

#[derive(Debug, Clone)]
pub struct Observation {{
    library: Arc<Library>,
    handle: u64,
    release_symbol: &'static str,
}}

impl Observation {{
    pub(crate) fn new(library: Arc<Library>, handle: u64, release_symbol: &'static str) -> Self {{
        Self {{ library, handle, release_symbol }}
    }}

    pub fn handle(&self) -> u64 {{
        self.handle
    }}

    pub fn cost_usd(&self) -> f64 {{
        unsafe {{
            let symbol: Symbol<unsafe extern "C" fn(u64) -> f64> = self
                .library
                .get(b"corvid_observation_cost_usd")
                .expect("resolve corvid_observation_cost_usd");
            symbol(self.handle)
        }}
    }}

    pub fn latency_ms(&self) -> u64 {{
        unsafe {{
            let symbol: Symbol<unsafe extern "C" fn(u64) -> u64> = self
                .library
                .get(b"corvid_observation_latency_ms")
                .expect("resolve corvid_observation_latency_ms");
            symbol(self.handle)
        }}
    }}

    pub fn tokens_in(&self) -> u64 {{
        unsafe {{
            let symbol: Symbol<unsafe extern "C" fn(u64) -> u64> = self
                .library
                .get(b"corvid_observation_tokens_in")
                .expect("resolve corvid_observation_tokens_in");
            symbol(self.handle)
        }}
    }}

    pub fn tokens_out(&self) -> u64 {{
        unsafe {{
            let symbol: Symbol<unsafe extern "C" fn(u64) -> u64> = self
                .library
                .get(b"corvid_observation_tokens_out")
                .expect("resolve corvid_observation_tokens_out");
            symbol(self.handle)
        }}
    }}

    pub fn exceeded_bound(&self) -> bool {{
        unsafe {{
            let symbol: Symbol<unsafe extern "C" fn(u64) -> bool> = self
                .library
                .get(b"corvid_observation_exceeded_bound")
                .expect("resolve corvid_observation_exceeded_bound");
            symbol(self.handle)
        }}
    }}
}}

impl Drop for Observation {{
    fn drop(&mut self) {{
        if self.handle == 0 {{
            return;
        }}
        unsafe {{
            if let Ok(symbol) =
                self.library.get::<unsafe extern "C" fn(u64)>(self.release_symbol.as_bytes())
            {{
                symbol(self.handle);
            }}
        }}
        self.handle = 0;
    }}
}}

#[derive(Debug, Clone)]
pub struct Grounded<T> {{
    payload: T,
    library: Arc<Library>,
    handle: u64,
    release_symbol: &'static str,
}}

impl<T> Grounded<T> {{
    pub(crate) fn new(
        payload: T,
        library: Arc<Library>,
        handle: u64,
        release_symbol: &'static str,
    ) -> Self {{
        Self {{
            payload,
            library,
            handle,
            release_symbol,
        }}
    }}

    pub fn payload(&self) -> &T {{
        &self.payload
    }}

    pub fn provenance(&self) -> GroundedProvenance<'_, T> {{
        GroundedProvenance {{ grounded: self }}
    }}
}}

impl<T> Drop for Grounded<T> {{
    fn drop(&mut self) {{
        if self.handle == 0 {{
            return;
        }}
        unsafe {{
            if let Ok(symbol) =
                self.library.get::<unsafe extern "C" fn(u64)>(self.release_symbol.as_bytes())
            {{
                symbol(self.handle);
            }}
        }}
        self.handle = 0;
    }}
}}

pub struct GroundedProvenance<'a, T> {{
    grounded: &'a Grounded<T>,
}}

impl<'a, T> GroundedProvenance<'a, T> {{
    pub fn confidence(&self) -> f64 {{
        unsafe {{
            let symbol: Symbol<unsafe extern "C" fn(u64) -> f64> = self
                .grounded
                .library
                .get(b"corvid_grounded_confidence")
                .expect("resolve corvid_grounded_confidence");
            symbol(self.grounded.handle)
        }}
    }}

    pub fn sources(&self) -> CorvidResult<Vec<String>> {{
        unsafe {{
            let symbol: Symbol<
                unsafe extern "C" fn(u64, *mut *const c_char, usize) -> i32,
            > = self
                .grounded
                .library
                .get(b"corvid_grounded_sources")
                .map_err(|err| CorvidError::Load(err.to_string()))?;
            let count = symbol(self.grounded.handle, std::ptr::null_mut(), 0);
            if count < 0 {{
                return Err(CorvidError::Runtime(
                    "runtime failed to enumerate grounded sources".to_string(),
                ));
            }}
            let mut out = vec![std::ptr::null(); count as usize];
            let written = symbol(self.grounded.handle, out.as_mut_ptr(), out.len());
            if written < 0 {{
                return Err(CorvidError::Runtime(
                    "runtime failed to read grounded sources".to_string(),
                ));
            }}
            Ok(out
                .into_iter()
                .take(written as usize)
                .map(read_c_string_lossy)
                .collect())
        }}
    }}
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Weak<T> {{
    pub value: T,
}}

pub(crate) fn read_c_string_lossy(ptr: *const c_char) -> String {{
    if ptr.is_null() {{
        return String::new();
    }}
    unsafe {{ CStr::from_ptr(ptr) }}.to_string_lossy().into_owned()
}}

pub(crate) fn take_owned_c_string(
    library: &Arc<Library>,
    ptr: *const c_char,
    free_symbol: &'static str,
) -> CorvidResult<String> {{
    if ptr.is_null() {{
        return Ok(String::new());
    }}
    let value = unsafe {{ CStr::from_ptr(ptr) }}
        .to_str()
        .map_err(|err| CorvidError::Decode(err.to_string()))?
        .to_string();
    unsafe {{
        let free: Symbol<unsafe extern "C" fn(*const c_char)> = library
            .get(free_symbol.as_bytes())
            .map_err(|err| CorvidError::Load(err.to_string()))?;
        free(ptr);
    }}
    Ok(value)
}}

pub(crate) fn hex_bytes(bytes: &[u8]) -> String {{
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {{
        use std::fmt::Write as _;
        let _ = write!(&mut out, "{{byte:02x}}");
    }}
    out
}}
"#,
        hash = context.descriptor_hash_hex,
        version = context.bind_version,
        generated_at = context.abi.generated_at
    )
}

fn render_types_rs(context: &BindingContext) -> String {
    let mut out = String::new();
    out.push_str("// @generated by corvid bind rust.\n");
    out.push_str(&format!(
        "// descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("// corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "// descriptor generated_at: {}\n\n",
        context.abi.generated_at
    ));
    out.push_str("use serde::{Deserialize, Serialize};\n\n");
    for ty in &context.abi.types {
        if ty.kind != "struct" {
            continue;
        }
        out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", pascal_case(&ty.name)));
        for field in &ty.fields {
            out.push_str(&format!(
                "    pub {}: {},\n",
                snake_case(&field.name),
                rust_public_type(&field.r#type)
            ));
        }
        out.push_str("}\n\n");
    }
    out
}

fn render_catalog_rs() -> String {
    r#"// @generated by corvid bind rust.
use std::ffi::c_char;

use libloading::Symbol;
use serde_json::json;

use crate::common::{
    read_c_string_lossy, Client, CorvidAgentHandleRaw, CorvidError, CorvidFindAgentsResultRaw,
    CorvidResult, TrustTier, CORVID_FIND_AGENTS_OK,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FindAgentsStatus {
    Ok,
    BadJson,
    UnknownDimension,
    OpMismatch,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reversibility {
    Reversible,
    Irreversible,
}

#[derive(Debug, Clone)]
pub struct AgentInfo {
    pub name: String,
    pub symbol: String,
    pub source_file: String,
    pub source_line: u32,
    pub trust_tier: TrustTier,
    pub cost_bound_usd: Option<f64>,
    pub reversible: Option<Reversibility>,
    pub replayable: bool,
    pub deterministic: bool,
    pub dangerous: bool,
    pub pub_extern_c: bool,
    pub requires_approval: bool,
    pub grounded_source_count: u32,
    pub param_count: u32,
}

pub struct Catalog<'a> {
    client: &'a Client,
}

pub struct CatalogQuery<'a> {
    client: &'a Client,
    clauses: Vec<serde_json::Value>,
}

impl<'a> Catalog<'a> {
    pub(crate) fn new(client: &'a Client) -> Self {
        Self { client }
    }

    pub fn query(&self) -> CatalogQuery<'a> {
        CatalogQuery {
            client: self.client,
            clauses: Vec::new(),
        }
    }

    pub fn where_trust_tier_le(&self, tier: TrustTier) -> CatalogQuery<'a> {
        self.query().where_trust_tier_le(tier)
    }

    pub fn where_cost_bound_usd_le(&self, usd: f64) -> CatalogQuery<'a> {
        self.query().where_cost_bound_usd_le(usd)
    }

    pub fn not_dangerous(&self) -> CatalogQuery<'a> {
        self.query().not_dangerous()
    }
}

impl<'a> CatalogQuery<'a> {
    fn push_clause(mut self, clause: serde_json::Value) -> Self {
        self.clauses.push(clause);
        self
    }

    pub fn where_trust_tier_le(self, tier: TrustTier) -> Self {
        let value = match tier {
            TrustTier::Autonomous => "autonomous",
            TrustTier::HumanRequired => "human_required",
            TrustTier::SecurityReview => "security_review",
        };
        self.push_clause(json!({"dim":"trust_tier","op":"le","value":value}))
    }

    pub fn where_cost_bound_usd_le(self, usd: f64) -> Self {
        self.push_clause(json!({"dim":"cost_bound_usd","op":"le","value":usd}))
    }

    pub fn where_latency_p99_ms_le(self, ms: f64) -> Self {
        self.push_clause(json!({"dim":"latency_p99_ms","op":"le","value":ms}))
    }

    pub fn not_dangerous(self) -> Self {
        self.push_clause(json!({"dim":"dangerous","op":"eq","value":false}))
    }

    pub fn replayable(self) -> Self {
        self.push_clause(json!({"dim":"replayable","op":"eq","value":true}))
    }

    pub fn deterministic(self) -> Self {
        self.push_clause(json!({"dim":"deterministic","op":"eq","value":true}))
    }

    pub fn find(self) -> CorvidResult<Vec<AgentInfo>> {
        let filter = if self.clauses.len() == 1 {
            self.clauses.into_iter().next().unwrap()
        } else {
            json!({ "all": self.clauses })
        };
        let filter_json = serde_json::to_string(&filter)
            .map_err(|err| CorvidError::Decode(err.to_string()))?;
        unsafe {
            let find: Symbol<
                unsafe extern "C" fn(*const c_char, usize, *mut usize, usize) -> CorvidFindAgentsResultRaw,
            > = self
                .client
                .library
                .get(b"corvid_find_agents_where")
                .map_err(|err| CorvidError::Load(err.to_string()))?;
            let list: Symbol<unsafe extern "C" fn(*mut CorvidAgentHandleRaw, usize) -> usize> = self
                .client
                .library
                .get(b"corvid_list_agents")
                .map_err(|err| CorvidError::Load(err.to_string()))?;

            let filter_json = std::ffi::CString::new(filter_json)
                .map_err(|err| CorvidError::BadArgs(err.to_string()))?;
            let raw = find(filter_json.as_ptr(), filter_json.as_bytes().len(), std::ptr::null_mut(), 0);
        if raw.status != CORVID_FIND_AGENTS_OK {
                return Err(CorvidError::Runtime(read_c_string_lossy(raw.error_message)));
            }
            let mut matched = vec![0usize; raw.matched_count];
            let raw = find(
                filter_json.as_ptr(),
                filter_json.as_bytes().len(),
                matched.as_mut_ptr(),
                matched.len(),
            );
            if raw.status != CORVID_FIND_AGENTS_OK {
                return Err(CorvidError::Runtime(read_c_string_lossy(raw.error_message)));
            }
            let total = list(std::ptr::null_mut(), 0);
            let mut handles = vec![
                CorvidAgentHandleRaw {
                    name: std::ptr::null(),
                    symbol: std::ptr::null(),
                    source_file: std::ptr::null(),
                    source_line: 0,
                    trust_tier: 0,
                    cost_bound_usd: 0.0,
                    reversible: 0,
                    latency_instant: 0,
                    replayable: 0,
                    deterministic: 0,
                    dangerous: 0,
                    pub_extern_c: 0,
                    requires_approval: 0,
                    grounded_source_count: 0,
                    param_count: 0,
                };
                total
            ];
            list(handles.as_mut_ptr(), handles.len());
            Ok(matched
                .into_iter()
                .filter_map(|index| handles.get(index).copied())
                .map(AgentInfo::from_raw)
                .collect())
        }
    }
}

impl AgentInfo {
    fn from_raw(raw: CorvidAgentHandleRaw) -> Self {
        Self {
            name: read_c_string_lossy(raw.name),
            symbol: read_c_string_lossy(raw.symbol),
            source_file: read_c_string_lossy(raw.source_file),
            source_line: raw.source_line,
            trust_tier: match raw.trust_tier {
                1 => TrustTier::HumanRequired,
                2 => TrustTier::SecurityReview,
                _ => TrustTier::Autonomous,
            },
            cost_bound_usd: if raw.cost_bound_usd.is_finite() {
                Some(raw.cost_bound_usd)
            } else {
                None
            },
            reversible: match raw.reversible {
                0 => Some(Reversibility::Reversible),
                1 => Some(Reversibility::Irreversible),
                _ => None,
            },
            replayable: raw.replayable != 0,
            deterministic: raw.deterministic != 0,
            dangerous: raw.dangerous != 0,
            pub_extern_c: raw.pub_extern_c != 0,
            requires_approval: raw.requires_approval != 0,
            grounded_source_count: raw.grounded_source_count,
            param_count: raw.param_count,
        }
    }
}
"#
    .to_string()
}

fn render_agent_module(context: &BindingContext, agent: &corvid_abi::AbiAgent) -> Result<String> {
    let marker = pascal_case(&agent.name);
    let api_trait = format!("{marker}Api");
    let method_name = snake_case(&agent.name);
    let return_type = if returns_grounded(&agent.return_type) {
        format!(
            "Grounded<{}>",
            rust_public_type(
                grounded_inner(agent.return_type()).unwrap_or(&agent.return_type)
            )
        )
    } else {
        rust_public_type(&agent.return_type)
    };

    let mut out = String::new();
    out.push_str("// @generated by corvid bind rust.\n");
    out.push_str(&format!(
        "// descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("// corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "// descriptor generated_at: {}\n",
        context.abi.generated_at
    ));
    out.push_str("use std::ffi::CString;\n\n");
    out.push_str("use libloading::Symbol;\n");
    out.push_str("use serde_json::json;\n\n");
    out.push_str("use crate::common::{\n");
    out.push_str("    take_owned_c_string, ApprovalDecision, Approver, CallAttempt, CallStatus, Client,\n");
    out.push_str("    CorvidError, CorvidResult, Grounded, Observation, TrustTier,\n");
    out.push_str("};\n");
    out.push_str("use crate::types::*;\n\n");
    out.push_str(&format!("pub struct {marker};\n\n"));
    out.push_str(&format!("impl {marker} {{\n"));
    out.push_str(&format!(
        "    pub const NAME: &str = {};\n",
        rust_string_literal(&agent.name)
    ));
    out.push_str(&format!(
        "    pub const SYMBOL: &str = {};\n",
        rust_string_literal(&agent.symbol)
    ));
    out.push_str(&format!(
        "    pub const TRUST_TIER: TrustTier = TrustTier::{};\n",
        match agent.abi_effect_trust_tier().as_deref() {
            Some("human_required") => "HumanRequired",
            Some("security_review") => "SecurityReview",
            _ => "Autonomous",
        }
    ));
    if let Some(budget) = &agent.budget {
        out.push_str(&format!(
            "    pub const COST_BOUND_USD: Option<f64> = Some({});\n",
            rust_f64_literal(budget.usd_per_call)
        ));
    } else {
        out.push_str("    pub const COST_BOUND_USD: Option<f64> = None;\n");
    }
    out.push_str(&format!(
        "    pub const IS_DANGEROUS: bool = {};\n",
        if agent.attributes.dangerous { "true" } else { "false" }
    ));
    out.push_str(&format!(
        "    pub const RETURNS_GROUNDED: bool = {};\n",
        if returns_grounded(&agent.return_type) { "true" } else { "false" }
    ));
    out.push_str("}\n\n");

    let generics = render_method_generics(agent);
    out.push_str(&format!("pub trait {api_trait} {{\n"));
    out.push_str(&format!(
        "    fn {method_name}{generics}(&self{sig}) -> CorvidResult<({return_type}, Observation)>;\n",
        generics = generics,
        sig = render_trait_signature_params(agent)
    ));
    out.push_str("}\n\n");
    out.push_str(&format!("impl {api_trait} for Client {{\n"));
    out.push_str(&format!(
        "    fn {method_name}{generics}(&self{sig}) -> CorvidResult<({return_type}, Observation)> {{\n",
        generics = generics,
        sig = render_trait_signature_params(agent)
    ));
    if agent.attributes.dangerous {
        out.push_str(&render_dangerous_agent_body(agent)?);
    } else {
        out.push_str(&render_direct_agent_body(agent)?);
    }
    out.push_str("    }\n");
    out.push_str("}\n");

    Ok(out)
}

trait AbiAgentExt {
    fn abi_effect_trust_tier(&self) -> Option<String>;
    fn return_type(&self) -> &corvid_abi::TypeDescription;
}

impl AbiAgentExt for corvid_abi::AbiAgent {
    fn abi_effect_trust_tier(&self) -> Option<String> {
        self.effects.trust_tier.clone()
    }

    fn return_type(&self) -> &corvid_abi::TypeDescription {
        &self.return_type
    }
}

fn grounded_inner(ty: &corvid_abi::TypeDescription) -> Option<&corvid_abi::TypeDescription> {
    match ty {
        corvid_abi::TypeDescription::Grounded { grounded } => Some(grounded.inner.as_ref()),
        _ => None,
    }
}

fn render_trait_signature_params(agent: &corvid_abi::AbiAgent) -> String {
    let mut out = String::new();
    for param in &agent.params {
        out.push_str(", ");
        out.push_str(&snake_case(&param.name));
        out.push_str(": ");
        out.push_str(&rust_public_param_type(param));
    }
    if agent.attributes.dangerous {
        out.push_str(", approver: &dyn Approver");
    }
    out
}

fn render_method_generics(agent: &corvid_abi::AbiAgent) -> String {
    let mut lifetimes = Vec::new();
    for param in &agent.params {
        let ownership = effective_param_ownership(param);
        if matches!(ownership.mode, corvid_abi::AbiOwnershipMode::Borrowed) {
            if let Some(lifetime) = ownership.lifetime.as_deref() {
                if lifetime != "call" && !lifetimes.iter().any(|existing| existing == lifetime) {
                    lifetimes.push(lifetime.to_string());
                }
            }
        }
    }
    if lifetimes.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            lifetimes
                .iter()
                .map(|lifetime| format!("'{lifetime}"))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn render_dangerous_agent_body(agent: &corvid_abi::AbiAgent) -> Result<String> {
    let mut out = String::new();
    out.push_str("        let args_json = json!([\n");
    for param in &agent.params {
        out.push_str(&format!("            {},\n", snake_case(&param.name)));
    }
    out.push_str("        ]);\n");
    out.push_str("        let args_json = serde_json::to_string(&args_json)\n");
    out.push_str("            .map_err(|err| CorvidError::Decode(err.to_string()))?;\n");
    out.push_str(&format!(
        "        match self.call_json_agent_once::<{}>({}, &args_json)? {{\n",
        rust_public_type(&agent.return_type),
        rust_string_literal(&agent.name)
    ));
    out.push_str("            CallAttempt::Completed(value) => Ok(value),\n");
    out.push_str("            CallAttempt::ApprovalRequired(request) => match approver.decide(&request) {\n");
    out.push_str("                ApprovalDecision::Reject => Err(CorvidError::ApprovalDenied(request)),\n");
    out.push_str("                ApprovalDecision::Accept => {\n");
    out.push_str("                    self.mark_preapproved_request(&request.site_name, &request.args_json)?;\n");
    out.push_str(&render_direct_invoke_body(agent, "                    ")?);
    out.push_str("                }\n");
    out.push_str("            },\n");
    out.push_str("        }\n");
    Ok(out)
}

fn render_direct_agent_body(agent: &corvid_abi::AbiAgent) -> Result<String> {
    render_direct_invoke_body(agent, "        ")
}

fn render_direct_invoke_body(agent: &corvid_abi::AbiAgent, indent: &str) -> Result<String> {
    let mut out = String::new();
    let return_ownership = effective_return_ownership(agent);
    let return_destructor = return_ownership
        .destructor
        .as_ref()
        .map(|destructor| destructor.symbol.as_str())
        .unwrap_or("corvid_free_string");
    let mut argtypes = Vec::new();
    let mut call_args = Vec::new();
    let mut prelude = String::new();
    for (index, param) in agent.params.iter().enumerate() {
        let ident = snake_case(&param.name);
        let ffi_type = rust_c_abi_param_type(&param.ty)?;
        argtypes.push(ffi_type.to_string());
        if matches!(
            crate::ffi_scalar_kind(&param.ty),
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId)
        ) {
            writeln!(
                &mut prelude,
                "{indent}let arg_{index} = CString::new({ident}).map_err(|err| CorvidError::BadArgs(err.to_string()))?;"
            )
            .unwrap();
            call_args.push(format!("arg_{index}.as_ptr()"));
        } else {
            call_args.push(ident);
        }
    }
    if returns_grounded(&agent.return_type) {
        argtypes.push("*mut u64".to_string());
    }
    argtypes.push("*mut u64".to_string());
    let return_ty = if returns_grounded(&agent.return_type) {
        rust_c_abi_return_type(grounded_inner(agent.return_type()).unwrap())?
    } else {
        rust_c_abi_return_type(&agent.return_type)?
    };
    let fn_sig = format!(
        "unsafe extern \"C\" fn({}) -> {}",
        argtypes.join(", "),
        return_ty
    );
    out.push_str(&prelude);
    out.push_str(&format!("{indent}unsafe {{\n"));
    let symbol_bytes = format!("b\"{}\"", agent.symbol);
    out.push_str(&format!(
        "{indent}    let symbol: Symbol<{fn_sig}> = self.library.get({symbol}).map_err(|err| CorvidError::Load(err.to_string()))?;\n",
        symbol = symbol_bytes
    ));
    if returns_grounded(&agent.return_type) {
        out.push_str(&format!("{indent}    let mut grounded_handle = 0u64;\n"));
    }
    out.push_str(&format!("{indent}    let mut observation_handle = 0u64;\n"));
    let mut all_args = call_args;
    if returns_grounded(&agent.return_type) {
        all_args.push("&mut grounded_handle".to_string());
    }
    all_args.push("&mut observation_handle".to_string());
    out.push_str(&format!(
        "{indent}    let value = symbol({});\n",
        all_args.join(", ")
    ));
    if returns_grounded(&agent.return_type) {
        match grounded_inner_kind(&agent.return_type).unwrap() {
            corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId => {
                out.push_str(&format!(
                    "{indent}    let payload = take_owned_c_string(&self.library, value, \"corvid_free_string\")?;\n",
                ));
            }
            _ => out.push_str(&format!("{indent}    let payload = value;\n")),
        }
        out.push_str(&format!(
            "{indent}    let grounded = Grounded::new(payload, self.library.clone(), grounded_handle, {:?});\n",
            return_destructor
        ));
        out.push_str(&format!(
            "{indent}    Ok((grounded, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
        ));
    } else {
        match crate::ffi_scalar_kind(&agent.return_type) {
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId) => {
                out.push_str(&format!(
                    "{indent}    let payload = take_owned_c_string(&self.library, value, {:?})?;\n",
                    return_destructor
                ));
                out.push_str(&format!(
                    "{indent}    Ok((payload, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
            Some(corvid_abi::ScalarTypeName::Nothing) => {
                out.push_str(&format!(
                    "{indent}    Ok(((), Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
            _ => {
                out.push_str(&format!(
                    "{indent}    Ok((value, Observation::new(self.library.clone(), observation_handle, \"corvid_observation_release\")))\n",
                ));
            }
        }
    }
    out.push_str(&format!("{indent}}}\n"));
    Ok(out)
}
