//! `corvid auth keys issue/revoke/rotate` — the API-key lifecycle
//! subcommand surface.
//!
//! Each operation opens the auth state via [`SessionAuthRuntime`]
//! and threads the runtime's typed records into a CLI-shaped
//! output. Issuance + rotation echo the raw key value once so the
//! operator captures it before the audit log redacts; revocation
//! is idempotent so re-running the command is safe.

use anyhow::{anyhow, Result};
use corvid_runtime::auth::{ApiKeyCreate, AuthActor, SessionAuthRuntime};
use std::path::PathBuf;

#[derive(Debug, Clone)]
pub struct AuthKeyIssueArgs {
    pub auth_state: PathBuf,
    pub key_id: String,
    pub service_actor_id: String,
    pub tenant_id: String,
    pub raw_key: String,
    pub scope_fingerprint: String,
    pub expires_at_ms: u64,
    /// Display name for the service actor record (created if missing).
    pub display_name: String,
}

#[derive(Debug, Clone, PartialEq)]
pub struct AuthKeyIssueOutput {
    pub key_id: String,
    pub service_actor_id: String,
    pub tenant_id: String,
    pub key_hash_prefix: String,
    pub scope_fingerprint: String,
    pub expires_at_ms: u64,
    pub raw_key: String,
}

/// Issue a new API key. The raw key value is supplied by the
/// caller (typically generated by an HMAC-SHA256 of a host RNG
/// seed elsewhere in the deploy pipeline) and stored only as an
/// Argon2id hash. The raw value is echoed back in the output once
/// — this is the operator's only chance to capture it.
pub fn run_auth_key_issue(args: AuthKeyIssueArgs) -> Result<AuthKeyIssueOutput> {
    let auth = SessionAuthRuntime::open(&args.auth_state)
        .map_err(|e| anyhow!("auth runtime init failed: {e}"))?;
    // Ensure the service actor exists (idempotent upsert).
    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);
    let actor = AuthActor {
        id: args.service_actor_id.clone(),
        tenant_id: args.tenant_id.clone(),
        display_name: args.display_name.clone(),
        actor_kind: "service".to_string(),
        auth_method: "api_key".to_string(),
        assurance_level: "service".to_string(),
        role_fingerprint: "service".to_string(),
        permission_fingerprint: args.scope_fingerprint.clone(),
        created_ms: now_ms,
        updated_ms: now_ms,
    };
    auth.upsert_actor(actor)
        .map_err(|e| anyhow!("upsert service actor: {e}"))?;
    let record = auth
        .create_api_key(ApiKeyCreate {
            id: args.key_id.clone(),
            service_actor_id: args.service_actor_id.clone(),
            tenant_id: args.tenant_id.clone(),
            raw_key: args.raw_key.clone(),
            scope_fingerprint: args.scope_fingerprint.clone(),
            expires_ms: args.expires_at_ms,
        })
        .map_err(|e| anyhow!("create api key: {e}"))?;
    Ok(AuthKeyIssueOutput {
        key_id: record.id,
        service_actor_id: record.service_actor_id,
        tenant_id: record.tenant_id,
        key_hash_prefix: record.key_hash.chars().take(16).collect(),
        scope_fingerprint: record.scope_fingerprint,
        expires_at_ms: record.expires_ms,
        // Echo once. The operator captures this and the raw value
        // never leaves the audit log.
        raw_key: args.raw_key,
    })
}

#[derive(Debug, Clone)]
pub struct AuthKeyRevokeArgs {
    pub auth_state: PathBuf,
    pub key_id: String,
}

#[derive(Debug, Clone, PartialEq)]
pub struct AuthKeyRevokeOutput {
    pub key_id: String,
    pub revoked_at_ms: u64,
}

/// Revoke a previously-issued API key. Idempotent — re-revoking a
/// revoked key returns the same `revoked_at_ms`.
pub fn run_auth_key_revoke(args: AuthKeyRevokeArgs) -> Result<AuthKeyRevokeOutput> {
    let auth = SessionAuthRuntime::open(&args.auth_state)
        .map_err(|e| anyhow!("auth runtime init failed: {e}"))?;
    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);
    let record = auth
        .revoke_api_key(&args.key_id, now_ms)
        .map_err(|e| anyhow!("revoke api key: {e}"))?;
    Ok(AuthKeyRevokeOutput {
        key_id: record.id,
        revoked_at_ms: record.revoked_ms.unwrap_or(now_ms),
    })
}

#[derive(Debug, Clone)]
pub struct AuthKeyRotateArgs {
    pub auth_state: PathBuf,
    pub key_id: String,
    pub service_actor_id: String,
    pub tenant_id: String,
    pub new_key_id: String,
    pub new_raw_key: String,
    pub expires_at_ms: u64,
}

#[derive(Debug, Clone, PartialEq)]
pub struct AuthKeyRotateOutput {
    pub revoked_key_id: String,
    pub new_key_id: String,
    pub raw_key: String,
    pub scope_fingerprint: String,
    pub expires_at_ms: u64,
}

/// Rotate an API key: revoke the old key, create a new key for the
/// same service actor with the same scope fingerprint. The
/// resulting raw key is echoed once.
pub fn run_auth_key_rotate(args: AuthKeyRotateArgs) -> Result<AuthKeyRotateOutput> {
    let auth = SessionAuthRuntime::open(&args.auth_state)
        .map_err(|e| anyhow!("auth runtime init failed: {e}"))?;
    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);
    let existing = auth
        .get_api_key(&args.key_id)
        .map_err(|e| anyhow!("get api key: {e}"))?
        .ok_or_else(|| anyhow!("api key `{}` not found", args.key_id))?;
    auth.revoke_api_key(&args.key_id, now_ms)
        .map_err(|e| anyhow!("revoke api key: {e}"))?;
    let new_record = auth
        .create_api_key(ApiKeyCreate {
            id: args.new_key_id.clone(),
            service_actor_id: args.service_actor_id.clone(),
            tenant_id: args.tenant_id.clone(),
            raw_key: args.new_raw_key.clone(),
            scope_fingerprint: existing.scope_fingerprint.clone(),
            expires_ms: args.expires_at_ms,
        })
        .map_err(|e| anyhow!("create rotated api key: {e}"))?;
    Ok(AuthKeyRotateOutput {
        revoked_key_id: args.key_id,
        new_key_id: new_record.id,
        raw_key: args.new_raw_key,
        scope_fingerprint: new_record.scope_fingerprint,
        expires_at_ms: new_record.expires_ms,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth_cmd::{run_auth_migrate, AuthMigrateArgs};
    use tempfile::tempdir;

    fn temp_paths() -> (tempfile::TempDir, PathBuf, PathBuf) {
        let dir = tempdir().unwrap();
        let auth = dir.path().join("auth.db");
        let approvals = dir.path().join("approvals.db");
        (dir, auth, approvals)
    }

    /// Slice 39L: `corvid auth keys issue` mints a key and echoes
    /// the raw value once.
    #[test]
    fn key_issue_creates_actor_and_returns_key() {
        let (_dir, auth, approvals) = temp_paths();
        run_auth_migrate(AuthMigrateArgs {
            auth_state: auth.clone(),
            approvals_state: approvals,
        })
        .unwrap();
        let out = run_auth_key_issue(AuthKeyIssueArgs {
            auth_state: auth,
            key_id: "k-1".to_string(),
            service_actor_id: "svc-1".to_string(),
            tenant_id: "tenant-1".to_string(),
            raw_key: "ck_test_secret_value".to_string(),
            scope_fingerprint: "scope:read".to_string(),
            expires_at_ms: u64::MAX,
            display_name: "Test Service".to_string(),
        })
        .expect("issue");
        assert_eq!(out.key_id, "k-1");
        assert_eq!(out.service_actor_id, "svc-1");
        assert_eq!(out.raw_key, "ck_test_secret_value");
        assert!(!out.key_hash_prefix.is_empty());
    }

    /// Slice 39L: `corvid auth keys revoke` flips the revoked
    /// timestamp.
    #[test]
    fn key_revoke_marks_revoked() {
        let (_dir, auth, approvals) = temp_paths();
        run_auth_migrate(AuthMigrateArgs {
            auth_state: auth.clone(),
            approvals_state: approvals,
        })
        .unwrap();
        run_auth_key_issue(AuthKeyIssueArgs {
            auth_state: auth.clone(),
            key_id: "k-1".to_string(),
            service_actor_id: "svc-1".to_string(),
            tenant_id: "tenant-1".to_string(),
            raw_key: "raw".to_string(),
            scope_fingerprint: "s".to_string(),
            expires_at_ms: u64::MAX,
            display_name: "n".to_string(),
        })
        .unwrap();
        let out = run_auth_key_revoke(AuthKeyRevokeArgs {
            auth_state: auth,
            key_id: "k-1".to_string(),
        })
        .expect("revoke");
        assert!(out.revoked_at_ms > 0);
    }

    /// Slice 39L: `corvid auth keys rotate` revokes the old key and
    /// creates a new one with the same scope fingerprint.
    #[test]
    fn key_rotate_revokes_old_and_creates_new() {
        let (_dir, auth, approvals) = temp_paths();
        run_auth_migrate(AuthMigrateArgs {
            auth_state: auth.clone(),
            approvals_state: approvals,
        })
        .unwrap();
        run_auth_key_issue(AuthKeyIssueArgs {
            auth_state: auth.clone(),
            key_id: "k-1".to_string(),
            service_actor_id: "svc-1".to_string(),
            tenant_id: "tenant-1".to_string(),
            raw_key: "raw-1".to_string(),
            scope_fingerprint: "scope:write".to_string(),
            expires_at_ms: u64::MAX,
            display_name: "n".to_string(),
        })
        .unwrap();
        let out = run_auth_key_rotate(AuthKeyRotateArgs {
            auth_state: auth,
            key_id: "k-1".to_string(),
            service_actor_id: "svc-1".to_string(),
            tenant_id: "tenant-1".to_string(),
            new_key_id: "k-2".to_string(),
            new_raw_key: "raw-2".to_string(),
            expires_at_ms: u64::MAX,
        })
        .expect("rotate");
        assert_eq!(out.revoked_key_id, "k-1");
        assert_eq!(out.new_key_id, "k-2");
        assert_eq!(out.scope_fingerprint, "scope:write");
        assert_eq!(out.raw_key, "raw-2");
    }
}
